// 50 additional campaigns (10 per category), each using one of the new creative styles.
// headline/intro: "Line one|Line two" (the second line is accented).
import { theme } from "./util.mjs";

export const NEW_BY_CATEGORY = {
  "ecommerce-retail": [
    {
      slug: "hygge-home-furniture", style: "editorial", title: "Nordic Home Furniture", brand: "Hygge & Co.",
      industry: "Home & Furniture", icon: "sofa",
      value: "Calm, magazine-style creative for handcrafted Scandinavian furniture.",
      keywords: ["furniture", "home", "interior", "scandinavian", "luxury"],
      intro: "Crafted|to Last", headline: "Slow Living,|Made Simple", sub: "Solid oak furniture, built by hand",
      cta: "Shop Collection", features: ["Solid European oak", "Hand-finished", "10-year guarantee"],
      theme: theme({ base: "#F4F1EA", text: "#2A2723", accent: "#5F7A61", accent2: "#C7784F", serif: true, radius: "0px" }),
    },
    {
      slug: "pxl-gaming-gear", style: "neon", title: "Pixel Arcade Gaming Gear", brand: "PXL Gear",
      industry: "Gaming Peripherals", icon: "gamepad",
      value: "Glitchy neon creative built to stop gamers mid-scroll.",
      keywords: ["gaming", "esports", "discount", "neon", "gear"],
      intro: "Level|Up", headline: "Pro Gaming|Gear Sale", sub: "Keyboards, mice & headsets",
      offer: ["35%", "OFF"], cta: "Level Up Now", features: ["RGB mechanical keys", "Ultra-light mice", "7.1 surround audio"],
      theme: theme({ base: "#07010F", text: "#F5F3FF", accent: "#FF2BD6", accent2: "#00F0FF" }),
    },
    {
      slug: "bloomly-flowers", style: "blob", title: "Bloom Flower Delivery", brand: "Bloomly",
      industry: "Gifting & Florals", icon: "flower",
      value: "Soft organic shapes for a same-day flower delivery offer.",
      keywords: ["flowers", "gifting", "delivery", "discount", "florist"],
      intro: "Say It With|Flowers", headline: "Same-Day|Flower Delivery", sub: "Hand-tied bouquets from local florists",
      offer: ["15%", "OFF"], cta: "Send Flowers", features: ["Local florists", "Same-day delivery", "Freshness guarantee"],
      theme: theme({ base: "#FFF7F0", text: "#3F1D2B", accent: "#EC4899", accent2: "#FB923C", onAccent: "#FFFFFF" }),
    },
    {
      slug: "mercato-weekend-sale", style: "ticker", title: "Mega Weekend Sale", brand: "Mercato",
      industry: "Department Store", icon: "tag",
      value: "Urgency-first ticker creative with a live countdown for a 48-hour sale.",
      keywords: ["sale", "discount", "weekend", "fashion", "urgency"],
      intro: "48 Hours|Only", headline: "Weekend|Mega Sale", sub: "Fashion, home & beauty",
      offer: ["70%", "OFF"], cta: "Shop the Sale", countdown: ["23", "59", "48"],
      theme: theme({ base: "#111111", text: "#FAFAFA", accent: "#FACC15", accent2: "#EF4444" }),
    },
    {
      slug: "aurum-fine-jewelry", style: "spotlight", title: "Aurum Fine Jewelry", brand: "Aurum",
      industry: "Fine Jewelry", icon: "diamond",
      value: "Jewel-box spotlight with light rays for a luxury gold collection.",
      keywords: ["luxury", "jewelry", "gold", "diamonds", "gifting"],
      intro: "Crafted|in Gold", headline: "The Eternity|Collection", sub: "18k gold & ethically sourced diamonds",
      cta: "Explore Pieces", features: ["18k solid gold", "Conflict-free stones", "Lifetime warranty"],
      theme: theme({ base: "#04241C", text: "#F5E6C4", accent: "#D4AF37", accent2: "#F5E6C4", serif: true, radius: "2px" }),
    },
    {
      slug: "snapfit-eyewear", style: "split", title: "SnapFit Eyewear", brand: "SnapFit",
      industry: "Eyewear D2C", icon: "glasses",
      value: "Bold split-panel creative promoting free home try-on.",
      keywords: ["eyewear", "glasses", "fashion", "free", "d2c"],
      intro: "See the|Difference", headline: "Try 5 Frames|at Home", sub: "Free home try-on & free shipping",
      offer: ["FREE", "TRY-ON"], cta: "Start Try-On", features: ["5 frames, 5 days", "Prescription ready", "Free returns"],
      theme: theme({ base: "#FFFFFF", text: "#0F172A", accent: "#2563EB", accent2: "#7C3AED" }),
    },
    {
      slug: "petpal-premium-food", style: "cards", title: "PetPal Premium Food", brand: "PetPal",
      industry: "Pet Care", icon: "paw",
      value: "Card-stack creative that sells a fresh pet food subscription feature by feature.",
      keywords: ["pets", "dog food", "subscription", "discount", "cats"],
      intro: "Happy Pets|Start Here", headline: "Vet-Approved|Pet Nutrition", sub: "Fresh recipes, delivered monthly",
      offer: ["30%", "1ST BOX"], cta: "Build a Box", features: ["Real meat first", "No fillers ever", "Delivered monthly"],
      theme: theme({ base: "#FFF8EC", text: "#422006", accent: "#EA580C", accent2: "#0D9488" }),
    },
    {
      slug: "voltra-ebikes", style: "data", variant: "line", title: "Voltra E-Bikes", brand: "Voltra",
      industry: "Micromobility", icon: "bike",
      value: "Data-driven creative that counts up real range stats for an e-bike launch.",
      keywords: ["ebike", "bikes", "electric", "commute", "test ride"],
      intro: "Ride|Further", headline: "E-Bikes|Built to Go", sub: "Test ride at a store near you",
      stat: ["120km", "range per charge"], cta: "Book Test Ride", features: ["120km range", "Folds in 10 seconds", "2-year warranty"],
      theme: theme({ base: "#0B1220", text: "#F1F5F9", accent: "#A3E635", accent2: "#22D3EE" }),
    },
    {
      slug: "glacier-outdoor-gear", style: "kinetic", title: "Glacier Outdoor Gear", brand: "Glacier",
      industry: "Outdoor Apparel", icon: "mountain",
      value: "Punchy kinetic-type creative for a summit-ready gear sale.",
      keywords: ["outdoor", "hiking", "apparel", "discount", "adventure"],
      intro: "Go|Wild", headline: "Gear for|Every Summit", sub: "Waterproof. Windproof. Tested.",
      offer: ["25%", "OFF"], cta: "Gear Up",
      theme: theme({ base: "#0B2239", text: "#F0F9FF", accent: "#F97316", accent2: "#7DD3FC" }),
    },
    {
      slug: "luma-smart-home", style: "split", flip: true, title: "Luma Smart Home", brand: "Luma",
      industry: "Smart Home", icon: "bulb",
      value: "Mirrored split creative for a smart lighting starter kit.",
      keywords: ["smart home", "lighting", "iot", "gadgets", "kit"],
      intro: "Lights,|Automated", headline: "Smart Lights|Starter Kit", sub: "Voice-assistant compatible",
      offer: ["$79", "KIT"], cta: "Shop the Kit", features: ["Voice-assistant ready", "16M colours", "Easy setup"],
      theme: theme({ base: "#0F0B1E", text: "#F5F3FF", accent: "#FACC15", accent2: "#8B5CF6" }),
    },
  ],

  "saas-tech": [
    {
      slug: "datapulse-analytics", style: "data", variant: "line", title: "DataPulse Analytics", brand: "DataPulse",
      industry: "Analytics SaaS", icon: "bars",
      value: "Live-drawing chart creative that proves speed-to-insight in seconds.",
      keywords: ["saas", "analytics", "data", "dashboards", "b2b"],
      intro: "Data|Without Delay", headline: "Real-Time|Analytics", sub: "Dashboards your whole team gets",
      stat: ["3.4x", "faster insights"], cta: "Start Free Trial", features: ["Live dashboards", "SQL + no-code", "SOC 2 Type II"],
      theme: theme({ base: "#0A0F1F", text: "#F8FAFC", accent: "#F472B6", accent2: "#60A5FA" }),
    },
    {
      slug: "codenest-deploy", style: "neon", title: "CodeNest Dev Platform", brand: "CodeNest",
      industry: "Developer Tools", icon: "code",
      value: "Terminal-green neon creative for a one-click deployment platform.",
      keywords: ["saas", "developer", "devops", "cloud", "deploy"],
      intro: "git push|→ Live", headline: "Deploy in|One Click", sub: "Preview URLs for every branch",
      cta: "Deploy Free", features: ["Global edge network", "Instant rollbacks", "Free SSL"],
      theme: theme({ base: "#030712", text: "#ECFDF5", accent: "#22C55E", accent2: "#A3E635" }),
    },
    {
      slug: "meetspace-video", style: "cards", title: "MeetSpace Video", brand: "MeetSpace",
      industry: "Collaboration SaaS", icon: "video",
      value: "Clean light card-stack creative listing video-call features.",
      keywords: ["saas", "video", "meetings", "remote", "collaboration"],
      intro: "Meet|Anywhere", headline: "Video Calls|That Just Work", sub: "No downloads, no time limits",
      cta: "Start a Meeting", features: ["HD video for 100", "AI meeting notes", "Works in browser"],
      theme: theme({ base: "#F8FAFC", text: "#0F172A", accent: "#0EA5E9", accent2: "#6366F1" }),
    },
    {
      slug: "inboxzero-ai", style: "kinetic", title: "InboxZero Email AI", brand: "InboxZero",
      industry: "AI Email Assistant", icon: "mail",
      value: "Kinetic type creative that makes inbox overload feel instantly solvable.",
      keywords: ["saas", "ai", "email", "productivity", "automation"],
      intro: "Inbox|Zero", headline: "Email on|Autopilot", sub: "AI drafts, sorts & follows up",
      cta: "Try It Free",
      theme: theme({ base: "#1E1B4B", text: "#EEF2FF", accent: "#FBBF24", accent2: "#F472B6" }),
    },
    {
      slug: "helix-crm", style: "split", title: "HelixCRM Sales Suite", brand: "Helix CRM",
      industry: "Sales CRM", icon: "users",
      value: "Split-panel creative that frames pipeline chaos, then the fix.",
      keywords: ["saas", "crm", "sales", "b2b", "pipeline"],
      intro: "Pipeline|Chaos?", headline: "Close Deals|Faster", sub: "AI-scored leads & auto follow-ups",
      cta: "Book a Demo", features: ["AI lead scoring", "Email sequences", "Revenue forecasts"],
      theme: theme({ base: "#0B1120", text: "#F1F5F9", accent: "#14B8A6", accent2: "#F59E0B" }),
    },
    {
      slug: "quantumcloud-hosting", style: "spotlight", title: "QuantumCloud Hosting", brand: "QuantumCloud",
      industry: "Cloud Infrastructure", icon: "server",
      value: "Spotlight creative that puts raw server speed centre stage.",
      keywords: ["saas", "hosting", "cloud", "servers", "developer"],
      intro: "Zero|Downtime", headline: "Blazing-Fast|Cloud Hosting", sub: "NVMe servers in 30 regions",
      offer: ["$5", "/MONTH"], cta: "Launch a Server", features: ["99.99% uptime", "DDoS protection", "Hourly billing"],
      theme: theme({ base: "#020617", text: "#F8FAFC", accent: "#818CF8", accent2: "#22D3EE" }),
    },
    {
      slug: "pixelforge-design", style: "blob", title: "PixelForge Design Tool", brand: "PixelForge",
      industry: "Design SaaS", icon: "pen",
      value: "Playful morphing-blob creative for a collaborative design tool.",
      keywords: ["saas", "design", "ui", "collaboration", "prototyping"],
      intro: "Design|Together", headline: "Collaborative|Design Tool", sub: "Prototype, review & hand off",
      cta: "Design Free", features: ["Real-time multiplayer", "Dev handoff", "Unlimited viewers"],
      theme: theme({ base: "#FAF5FF", text: "#2E1065", accent: "#A855F7", accent2: "#F97316", onAccent: "#FFFFFF" }),
    },
    {
      slug: "lingua-ai-translate", style: "editorial", title: "LinguaAI Translate", brand: "LinguaAI",
      industry: "AI Translation", icon: "globe",
      value: "Editorial serif creative that sells nuance, not just translation.",
      keywords: ["saas", "ai", "translation", "language", "localization"],
      intro: "Speak|Every Language", headline: "Translate With|Human Nuance", sub: "100+ languages, context-aware",
      cta: "Translate Free",
      theme: theme({ base: "#FFFBF5", text: "#1C1917", accent: "#B91C1C", accent2: "#1D4ED8", radius: "0px" }),
    },
    {
      slug: "securevault-passwords", style: "ticker", title: "SecureVault Passwords", brand: "SecureVault",
      industry: "Cybersecurity", icon: "lock",
      value: "Countdown-driven creative that turns password hygiene into a limited-time deal.",
      keywords: ["saas", "security", "passwords", "discount", "privacy"],
      intro: "Stop Reusing|Passwords", headline: "Password|Manager Sale", sub: "Encrypted vault for every device",
      offer: ["50%", "OFF"], cta: "Secure My Logins", countdown: ["11", "42", "37"],
      theme: theme({ base: "#0C0A09", text: "#FAFAF9", accent: "#F97316", accent2: "#FACC15" }),
    },
    {
      slug: "stackly-nocode", style: "data", variant: "bars", title: "Stackly No-Code", brand: "Stackly",
      industry: "No-Code Platform", icon: "blocks",
      value: "Rising bar-chart creative that quantifies faster app delivery.",
      keywords: ["saas", "no-code", "apps", "startups", "productivity"],
      intro: "Build Apps|Without Code", headline: "No-Code|App Builder", sub: "Drag, drop & publish in a day",
      stat: ["10x", "faster app builds"], cta: "Build Free", features: ["100+ templates", "Built-in database", "One-click publish"],
      theme: theme({ base: "#FFFFFF", text: "#111827", accent: "#4F46E5", accent2: "#10B981" }),
    },
  ],

  "real-estate": [
    {
      slug: "verde-eco-homes", style: "blob", title: "Verde Eco Homes", brand: "Verde Homes",
      industry: "Sustainable Housing", icon: "ecohouse",
      value: "Organic, nature-toned creative for net-zero family homes.",
      keywords: ["real estate", "eco", "homes", "sustainable", "family"],
      intro: "Live|Sustainably", headline: "Net-Zero|Family Homes", sub: "Solar-powered, energy-smart living",
      cta: "Tour Show Home", features: ["Solar + battery", "Heat-pump heating", "EV charging"],
      theme: theme({ base: "#F0FDF4", text: "#14532D", accent: "#16A34A", accent2: "#A3E635", onAccent: "#FFFFFF" }),
    },
    {
      slug: "marina-bay-towers", style: "data", variant: "line", title: "Marina Bay Towers", brand: "Marina Towers",
      industry: "Investment Property", icon: "marina",
      value: "Yield-chart creative that speaks directly to property investors.",
      keywords: ["real estate", "investment", "waterfront", "condos", "yield"],
      intro: "Waterfront|Returns", headline: "Waterfront|Investment", sub: "Luxury condos with rental management",
      stat: ["8.2%", "projected yield"], cta: "Get Brochure", legal: "Projections not guaranteed.",
      features: ["Managed rentals", "Marina views", "Completion 2027"],
      theme: theme({ base: "#06243A", text: "#F0FDFA", accent: "#2DD4BF", accent2: "#FDE68A" }),
    },
    {
      slug: "atelier-nord-architects", style: "editorial", title: "Atelier Nord Architects", brand: "Atelier Nord",
      industry: "Architecture Studio", icon: "compass",
      value: "Magazine-grade editorial creative for an architecture practice.",
      keywords: ["architecture", "design", "studio", "luxury", "commercial"],
      intro: "Form|Follows Life", headline: "Architecture|With Intent", sub: "Residential & commercial design",
      cta: "View Portfolio",
      theme: theme({ base: "#F5F5F4", text: "#1C1917", accent: "#B45309", accent2: "#57534E", radius: "0px" }),
    },
    {
      slug: "summit-ski-chalets", style: "split", title: "Summit Ski Chalets", brand: "Summit Chalets",
      industry: "Alpine Resort Homes", icon: "cabin",
      value: "Cold-toned split creative for ski-in, ski-out chalet stays.",
      keywords: ["real estate", "ski", "chalet", "luxury", "vacation"],
      intro: "Ski-In,|Ski-Out", headline: "Alpine|Chalets", sub: "Fireplaces, hot tubs & mountain views",
      cta: "Reserve a Chalet", features: ["Private hot tub", "Ski-in access", "Chef on request"],
      theme: theme({ base: "#0F172A", text: "#F8FAFC", accent: "#38BDF8", accent2: "#E2E8F0" }),
    },
    {
      slug: "nest-student-living", style: "kinetic", title: "Nest Student Living", brand: "Nest",
      industry: "Student Housing", icon: "key",
      value: "Loud kinetic-type creative aimed at students hunting for rooms.",
      keywords: ["real estate", "student", "rental", "housing", "discount"],
      intro: "Your Room|Awaits", headline: "Rooms Near|Campus", sub: "All bills included · Gym · Wi-Fi",
      offer: ["$0", "DEPOSIT"], cta: "Book a Room",
      theme: theme({ base: "#1D1D1D", text: "#FAFAFA", accent: "#FF6B35", accent2: "#FFE66D" }),
    },
    {
      slug: "harbor-point-prelaunch", style: "ticker", title: "Harbor Point Pre-Launch", brand: "Harbor Point",
      industry: "New Developments", icon: "crane",
      value: "Ticker creative with a countdown to close early-bird pricing.",
      keywords: ["real estate", "condos", "pre-launch", "discount", "investment"],
      intro: "Pre-Launch|Pricing", headline: "Early-Bird|Condo Offer", sub: "Only 40 units at launch prices",
      offer: ["10%", "EARLY BIRD"], cta: "Register Now", legal: "T&Cs apply.",
      countdown: ["02", "14", "35"], cdLabels: ["DAYS", "HRS", "MIN"],
      theme: theme({ base: "#0B1B2B", text: "#F8FAFC", accent: "#F59E0B", accent2: "#38BDF8" }),
    },
    {
      slug: "crestview-family-homes", style: "cards", title: "Crestview Family Homes", brand: "Crestview",
      industry: "Residential Sales", icon: "house",
      value: "Feature-card creative that walks families through a home's best bits.",
      keywords: ["real estate", "homes", "family", "open house", "residential"],
      intro: "Room to|Grow", headline: "Family Homes|From $499K", sub: "Open house this Saturday",
      cta: "Book a Viewing", features: ["4 bedrooms", "Top-rated schools", "Private garden"],
      theme: theme({ base: "#FFFBEB", text: "#292524", accent: "#EA580C", accent2: "#0891B2" }),
    },
    {
      slug: "neon-district-lofts", style: "neon", title: "Neon District Lofts", brand: "Neon District",
      industry: "Urban Rentals", icon: "nightcity",
      value: "After-dark neon creative for nightlife-ready city lofts.",
      keywords: ["real estate", "lofts", "rental", "urban", "nightlife"],
      intro: "Live|Loud", headline: "Downtown|Lofts", sub: "Rooftop bar · 24/7 gym · Co-working",
      cta: "Tour Tonight", features: ["Rooftop bar", "24/7 gym", "Co-working lounge"],
      theme: theme({ base: "#0A0014", text: "#FDF4FF", accent: "#F0ABFC", accent2: "#22D3EE" }),
    },
    {
      slug: "horizon-coworking", style: "split", flip: true, title: "Horizon Coworking", brand: "Horizon Work",
      industry: "Flexible Workspace", icon: "desk",
      value: "Mirrored split creative with a free day-pass hook.",
      keywords: ["real estate", "coworking", "office", "flexible", "free"],
      intro: "Work|Anywhere", headline: "Flexible|Coworking", sub: "Day passes to private offices",
      offer: ["1 DAY", "FREE PASS"], cta: "Claim Free Day", features: ["Hot desks & suites", "Meeting rooms", "Barista coffee"],
      theme: theme({ base: "#F8FAFC", text: "#0F172A", accent: "#E11D48", accent2: "#FB7185" }),
    },
    {
      slug: "palazzo-heritage", style: "spotlight", title: "Palazzo Heritage Residences", brand: "Palazzo",
      industry: "Heritage Restoration", icon: "columns",
      value: "Spotlit, gilded creative for restored landmark apartments.",
      keywords: ["real estate", "heritage", "luxury", "architecture", "apartments"],
      intro: "History,|Restored", headline: "Heritage|Residences", sub: "Restored 1890s landmark apartments",
      cta: "Private Viewing", features: ["Original frescoes", "Concierge & valet", "Private courtyard"],
      theme: theme({ base: "#1A1410", text: "#F5E6C4", accent: "#D6B370", accent2: "#F5E6C4", serif: true, radius: "2px" }),
    },
  ],

  "finance-crypto": [
    {
      slug: "bitvault-wallet", style: "neon", title: "BitVault Crypto Wallet", brand: "BitVault",
      industry: "Crypto Custody", icon: "bitcoin",
      value: "High-voltage neon creative for a self-custody crypto wallet.",
      keywords: ["crypto", "bitcoin", "wallet", "security", "web3"],
      intro: "Your Keys.|Your Coins.", headline: "Self-Custody|Crypto Wallet", sub: "Multi-chain, hardware-grade security",
      cta: "Get BitVault", legal: "Crypto assets are volatile.", features: ["20+ chains", "Biometric unlock", "Open-source"],
      theme: theme({ base: "#05010A", text: "#FFF7ED", accent: "#F7931A", accent2: "#A855F7" }),
    },
    {
      slug: "roundup-investing", style: "data", variant: "bars", title: "RoundUp Micro-Investing", brand: "RoundUp",
      industry: "Micro-Investing", icon: "coins",
      value: "Count-up savings creative that makes spare change feel significant.",
      keywords: ["finance", "investing", "savings", "fintech", "app"],
      intro: "Spare|Change?", headline: "Invest Your|Spare Change", sub: "Round up every purchase automatically",
      stat: ["$1,284", "saved in a year"], cta: "Start Saving", legal: "Capital at risk. Illustrative figure.",
      features: ["Automatic round-ups", "Diversified ETFs", "Withdraw anytime"],
      theme: theme({ base: "#F0FDFA", text: "#042F2E", accent: "#0D9488", accent2: "#F59E0B" }),
    },
    {
      slug: "loanleaf-mortgages", style: "blob", title: "LoanLeaf Mortgages", brand: "LoanLeaf",
      industry: "Mortgage Lending", icon: "mortgage",
      value: "Friendly, organic creative that softens a mortgage rate message.",
      keywords: ["finance", "mortgage", "home loan", "rates", "property"],
      intro: "Home Sweet|Home Loan", headline: "Mortgage Rates|From 5.1% APR", sub: "Pre-approval in 10 minutes",
      cta: "Check My Rate", legal: "Rates subject to approval.", features: ["No broker fees", "Fixed & variable", "Online approval"],
      theme: theme({ base: "#F7FEE7", text: "#1A2E05", accent: "#65A30D", accent2: "#0EA5E9", onAccent: "#FFFFFF" }),
    },
    {
      slug: "stellar-credit-card", style: "spotlight", title: "Stellar Credit Card", brand: "Stellar",
      industry: "Credit Cards", icon: "cardstar",
      value: "Premium spotlight creative that makes a metal card feel like a trophy.",
      keywords: ["finance", "credit card", "cashback", "rewards", "premium"],
      intro: "Metal Card.|Real Rewards.", headline: "3% Cashback|on Everything", sub: "No annual fee in year one",
      cta: "Apply Now", features: ["Metal card", "No FX fees", "Lounge access"], legal: "Terms apply. Subject to status.",
      theme: theme({ base: "#0B0B1A", text: "#F1F5F9", accent: "#C7D2FE", accent2: "#818CF8" }),
    },
    {
      slug: "taxease-filing", style: "ticker", title: "TaxEase Filing", brand: "TaxEase",
      industry: "Tax Software", icon: "calendar",
      value: "Deadline countdown creative that drives last-minute tax filing.",
      keywords: ["finance", "tax", "deadline", "free", "software"],
      intro: "Deadline|Approaching", headline: "File Taxes|in 15 Minutes", sub: "Step-by-step guided filing",
      offer: ["$0", "FEDERAL"], cta: "File Free Now", countdown: ["06", "23", "41"], cdLabels: ["DAYS", "HRS", "MIN"],
      theme: theme({ base: "#F8FAFC", text: "#0F172A", accent: "#2563EB", accent2: "#DC2626" }),
    },
    {
      slug: "greenyield-esg", style: "editorial", title: "GreenYield ESG Fund", brand: "GreenYield",
      industry: "Sustainable Investing", icon: "leafchart",
      value: "Considered editorial creative for purpose-led investors.",
      keywords: ["finance", "esg", "investing", "sustainable", "funds"],
      intro: "Invest With|Purpose", headline: "Sustainable|ESG Portfolios", sub: "Screened for climate & governance",
      cta: "Explore Funds", legal: "Investments are subject to market risk.",
      theme: theme({ base: "#F7F5EF", text: "#1F2A1F", accent: "#3F6212", accent2: "#B45309", radius: "0px" }),
    },
    {
      slug: "swiftsend-remittance", style: "split", title: "SwiftSend Remittance", brand: "SwiftSend",
      industry: "Money Transfer", icon: "plane",
      value: "Split-panel creative promising fast, fair cross-border transfers.",
      keywords: ["finance", "remittance", "transfer", "fintech", "free"],
      intro: "Money Home|in Minutes", headline: "Send Money|Worldwide", sub: "Low fees, real exchange rate",
      offer: ["$0", "1ST TRANSFER"], cta: "Send Now", features: ["80+ countries", "Real exchange rate", "Track every transfer"],
      theme: theme({ base: "#FFFFFF", text: "#111827", accent: "#7C3AED", accent2: "#22C55E" }),
    },
    {
      slug: "fortis-business-loans", style: "cards", title: "Fortis Business Loans", brand: "Fortis Capital",
      industry: "SME Lending", icon: "briefcase",
      value: "Card-stack creative that answers a business owner's three big questions.",
      keywords: ["finance", "business", "loans", "sme", "funding"],
      intro: "Grow|Your Business", headline: "Business Loans|Made Simple", sub: "Funding decisions in 24 hours",
      cta: "Get Funded", legal: "Subject to credit approval.", features: ["Up to $250K", "Decision in 24h", "No hidden fees"],
      theme: theme({ base: "#0B1324", text: "#F1F5F9", accent: "#3B82F6", accent2: "#FBBF24" }),
    },
    {
      slug: "coinpulse-exchange", style: "kinetic", title: "CoinPulse Exchange", brand: "CoinPulse",
      industry: "Crypto Exchange", icon: "pulsecoin",
      value: "Fast-cut kinetic creative for a low-fee crypto exchange.",
      keywords: ["crypto", "exchange", "trading", "bonus", "bitcoin"],
      intro: "Buy. Sell.|Hold.", headline: "Trade 300+|Crypto Assets", sub: "Low fees on major pairs",
      offer: ["$20", "BONUS"], cta: "Sign Up", legal: "Crypto is high risk.",
      theme: theme({ base: "#000000", text: "#F8FAFC", accent: "#00E676", accent2: "#FF3D71" }),
    },
    {
      slug: "pensionplus-retirement", style: "data", variant: "line", title: "PensionPlus Retirement", brand: "PensionPlus",
      industry: "Retirement Planning", icon: "hourglass",
      value: "Growth-curve creative that visualises a retirement pot compounding.",
      keywords: ["finance", "retirement", "pension", "investing", "planning"],
      intro: "Plan|Ahead", headline: "Retire on|Your Terms", sub: "Personalised retirement plans",
      stat: ["$1.2M", "projected at 65"], cta: "Plan My Future", legal: "Projections are illustrative only.",
      features: ["Tax-efficient", "Auto-rebalancing", "Advisor on call"],
      theme: theme({ base: "#FFF7ED", text: "#431407", accent: "#EA580C", accent2: "#0369A1" }),
    },
  ],

  "healthcare-fitness": [
    {
      slug: "zenflow-yoga", style: "blob", title: "ZenFlow Yoga Studio", brand: "ZenFlow",
      industry: "Yoga & Wellness", icon: "lotus",
      value: "Calm, organic creative that invites beginners to a first free class.",
      keywords: ["health", "yoga", "fitness", "wellness", "free"],
      intro: "Breathe|In", headline: "Find Your|Flow", sub: "Classes for every level, every day",
      offer: ["1ST", "CLASS FREE"], cta: "Book a Class", features: ["All levels welcome", "Heated studio", "Mats included"],
      theme: theme({ base: "#F4F7F2", text: "#273322", accent: "#6B8F5E", accent2: "#E9B384", onAccent: "#FFFFFF", serif: true }),
    },
    {
      slug: "ironcore-gym", style: "kinetic", title: "IronCore Gym", brand: "IronCore",
      industry: "Gyms & Fitness", icon: "dumbbell",
      value: "Aggressive kinetic type built for a gym membership push.",
      keywords: ["fitness", "gym", "workout", "discount", "membership"],
      intro: "No|Excuses", headline: "Stronger|Every Rep", sub: "24/7 access · Pro coaches",
      offer: ["$1", "1ST MONTH"], cta: "Join Now",
      theme: theme({ base: "#0A0A0A", text: "#FAFAFA", accent: "#EAB308", accent2: "#EF4444" }),
    },
    {
      slug: "mindease-therapy", style: "editorial", title: "MindEase Therapy", brand: "MindEase",
      industry: "Mental Health", icon: "chatheart",
      value: "Gentle editorial creative that lowers the barrier to starting therapy.",
      keywords: ["health", "therapy", "mental health", "wellness", "online"],
      intro: "You Don't|Have to Wait", headline: "Online Therapy|That Fits", sub: "Licensed therapists, same-week sessions",
      cta: "Get Matched", legal: "Not for emergencies.",
      theme: theme({ base: "#F8F7FF", text: "#1E1B4B", accent: "#6D28D9", accent2: "#0D9488", radius: "0px" }),
    },
    {
      slug: "hydrapure-bottle", style: "spotlight", title: "HydraPure Smart Bottle", brand: "HydraPure",
      industry: "Health Tech", icon: "bottle",
      value: "Spotlit product-hero creative for a self-cleaning bottle.",
      keywords: ["health", "hydration", "gadgets", "discount", "wellness"],
      intro: "Stay|Hydrated", headline: "Self-Cleaning|Smart Bottle", sub: "UV-C purifies in 60 seconds",
      offer: ["20%", "OFF"], cta: "Shop HydraPure", features: ["UV-C self-cleaning", "Cold for 24 hours", "Sip reminders"],
      theme: theme({ base: "#04121F", text: "#F0F9FF", accent: "#38BDF8", accent2: "#A7F3D0" }),
    },
    {
      slug: "carelink-telehealth", style: "split", title: "CareLink Telehealth", brand: "CareLink",
      industry: "Telehealth", icon: "stetho",
      value: "Reassuring split creative for on-demand video doctor visits.",
      keywords: ["health", "telehealth", "doctor", "healthcare", "online"],
      intro: "Doctor|On Demand", headline: "See a Doctor|in 15 Min", sub: "24/7 video visits from home",
      offer: ["$29", "VISIT"], cta: "Start a Visit", features: ["Board-certified doctors", "Prescriptions sent", "Open 24/7"],
      theme: theme({ base: "#FFFFFF", text: "#0B2545", accent: "#0284C7", accent2: "#10B981" }),
    },
    {
      slug: "runclub-marathon", style: "ticker", title: "RunClub City Marathon", brand: "RunClub",
      industry: "Sports Events", icon: "runner",
      value: "Race-day countdown ticker that fills registration before early-bird closes.",
      keywords: ["fitness", "running", "marathon", "event", "sports"],
      intro: "Race Day|Is Coming", headline: "City Marathon|Registration", sub: "Early-bird entries closing soon",
      offer: ["42K", "RACE"], cta: "Register Now", countdown: ["21", "08", "45"], cdLabels: ["DAYS", "HRS", "MIN"],
      theme: theme({ base: "#111827", text: "#F9FAFB", accent: "#F97316", accent2: "#FDE047" }),
    },
    {
      slug: "vitaboost-supplements", style: "cards", title: "VitaBoost Supplements", brand: "VitaBoost",
      industry: "Nutrition & Supplements", icon: "capsule",
      value: "Card-stack creative that sells personalised vitamin packs.",
      keywords: ["health", "vitamins", "supplements", "subscription", "discount"],
      intro: "Feel Your|Best", headline: "Personalised|Vitamin Packs", sub: "Quiz-matched, delivered monthly",
      offer: ["50%", "1ST MONTH"], cta: "Take the Quiz", features: ["Vitamin D3 + K2", "Omega-3", "Daily multi"],
      theme: theme({ base: "#FFFBEB", text: "#451A03", accent: "#D97706", accent2: "#E11D48" }),
    },
    {
      slug: "sleepwell-mattress", style: "data", variant: "line", title: "SleepWell Smart Mattress", brand: "SleepWell",
      industry: "Sleep Tech", icon: "moon",
      value: "Night-mode data creative that charts better sleep scores.",
      keywords: ["health", "sleep", "mattress", "smart home", "wellness"],
      intro: "Sleep|Smarter", headline: "Smart Sleep|Mattress", sub: "Temperature control & sleep insights",
      stat: ["92", "avg. sleep score"], cta: "Try 100 Nights", features: ["Dual-zone cooling", "Sleep tracking", "100-night trial"],
      theme: theme({ base: "#0B1026", text: "#EEF2FF", accent: "#A78BFA", accent2: "#FDE68A" }),
    },
    {
      slug: "pulseride-spin", style: "neon", title: "PulseRide Spin Bike", brand: "PulseRide",
      industry: "Connected Fitness", icon: "spin",
      value: "Studio-light neon creative for live at-home spin classes.",
      keywords: ["fitness", "spin", "cycling", "home workout", "classes"],
      intro: "Ride|Live", headline: "Live Spin|Classes at Home", sub: "Leaderboards · 1,000+ classes",
      cta: "Start Riding", features: ["Live leaderboards", "1,000+ classes", "Compact frame"],
      theme: theme({ base: "#0A0A0F", text: "#FFF1F2", accent: "#FF2E63", accent2: "#08D9D6" }),
    },
    {
      slug: "smilebright-whitening", style: "kinetic", title: "SmileBright Whitening", brand: "SmileBright",
      industry: "Dental Care", icon: "smile",
      value: "Bright, light-mode kinetic creative for an at-home whitening kit.",
      keywords: ["health", "dental", "whitening", "beauty", "discount"],
      intro: "Whiter|Smile", headline: "Whiter Teeth|at Home", sub: "Enamel-safe LED whitening kit",
      offer: ["40%", "OFF"], cta: "Get My Kit",
      theme: theme({ base: "#FFFFFF", text: "#0C4A6E", accent: "#0891B2", accent2: "#F472B6" }),
    },
  ],
};
