/* Generated by tools/build-ads.mjs — edit campaigns there and re-run: node tools/build-ads.mjs */
window.ADSTUDIO = {
  "gsap": {
    "version": "3.12.2",
    "url": "https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.2/gsap.min.js",
    "kb": {
      "min": 69.8,
      "gzip": 27.1
    }
  },
  "clickTag": "https://www.google.com",
  "animation": {
    "loop": 6,
    "plays": 2,
    "pause": 1,
    "total": 13
  },
  "categories": [
    {
      "slug": "ecommerce-retail",
      "label": "E-Commerce & Retail"
    },
    {
      "slug": "saas-tech",
      "label": "SaaS & Tech"
    },
    {
      "slug": "real-estate",
      "label": "Real Estate & Architecture"
    },
    {
      "slug": "finance-crypto",
      "label": "Finance & Crypto"
    },
    {
      "slug": "healthcare-fitness",
      "label": "Healthcare & Fitness"
    }
  ],
  "campaigns": [
    {
      "id": 1,
      "slug": "sneaker-drop",
      "title": "Sneaker Drop",
      "brand": "Stride",
      "category": "ecommerce-retail",
      "categoryLabel": "E-Commerce & Retail",
      "industry": "Footwear Retail",
      "value": "Limited-edition runner launch driven by flash pricing and scarcity messaging.",
      "keywords": [
        "sneakers",
        "discount",
        "flash sale",
        "fashion",
        "retail"
      ],
      "cta": "Shop Now",
      "accent": "#FF3D5A",
      "border": "#333",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/ecommerce-retail/sneaker-drop/300x250/index.html",
          "kb": 6.2
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/ecommerce-retail/sneaker-drop/728x90/index.html",
          "kb": 6
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/ecommerce-retail/sneaker-drop/160x600/index.html",
          "kb": 7.4
        }
      }
    },
    {
      "id": 2,
      "slug": "cyber-monday-gadgets",
      "title": "Cyber Monday Gadgets",
      "brand": "Voltix",
      "category": "ecommerce-retail",
      "categoryLabel": "E-Commerce & Retail",
      "industry": "Consumer Electronics",
      "value": "Doorbuster electronics event with bold neon styling and deep-discount hooks.",
      "keywords": [
        "cyber monday",
        "discount",
        "electronics",
        "gadgets",
        "deals"
      ],
      "cta": "Grab the Deal",
      "accent": "#22D3EE",
      "border": "#333",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/ecommerce-retail/cyber-monday-gadgets/300x250/index.html",
          "kb": 6.2
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/ecommerce-retail/cyber-monday-gadgets/728x90/index.html",
          "kb": 6.1
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/ecommerce-retail/cyber-monday-gadgets/160x600/index.html",
          "kb": 7.4
        }
      }
    },
    {
      "id": 3,
      "slug": "luxury-fashion-autumn",
      "title": "Luxury Fashion Autumn",
      "brand": "Maison Aurèle",
      "category": "ecommerce-retail",
      "categoryLabel": "E-Commerce & Retail",
      "industry": "Luxury Apparel",
      "value": "Editorial, serif-led seasonal campaign for a premium cashmere collection.",
      "keywords": [
        "luxury",
        "fashion",
        "autumn",
        "apparel",
        "premium"
      ],
      "cta": "Discover Now",
      "accent": "#8C5A3C",
      "border": "#e2e8f0",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/ecommerce-retail/luxury-fashion-autumn/300x250/index.html",
          "kb": 5.7
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/ecommerce-retail/luxury-fashion-autumn/728x90/index.html",
          "kb": 5.9
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/ecommerce-retail/luxury-fashion-autumn/160x600/index.html",
          "kb": 6.9
        }
      }
    },
    {
      "id": 4,
      "slug": "organic-coffee-roasters",
      "title": "Organic Coffee Roasters",
      "brand": "Ember & Oak",
      "category": "ecommerce-retail",
      "categoryLabel": "E-Commerce & Retail",
      "industry": "Food & Beverage D2C",
      "value": "Warm, craft-led subscription offer for fresh-roasted single-origin beans.",
      "keywords": [
        "coffee",
        "organic",
        "subscription",
        "discount",
        "d2c"
      ],
      "cta": "Order Fresh",
      "accent": "#E0A96D",
      "border": "#333",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/ecommerce-retail/organic-coffee-roasters/300x250/index.html",
          "kb": 6.3
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/ecommerce-retail/organic-coffee-roasters/728x90/index.html",
          "kb": 6.1
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/ecommerce-retail/organic-coffee-roasters/160x600/index.html",
          "kb": 7.5
        }
      }
    },
    {
      "id": 5,
      "slug": "cloudops-monitoring",
      "title": "CloudOps Monitoring",
      "brand": "CloudOps",
      "category": "saas-tech",
      "categoryLabel": "SaaS & Tech",
      "industry": "DevOps SaaS",
      "value": "Developer-focused trial acquisition for a full-stack observability platform.",
      "keywords": [
        "saas",
        "monitoring",
        "devops",
        "cloud",
        "b2b"
      ],
      "cta": "Start Free Trial",
      "accent": "#34D399",
      "border": "#333",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/saas-tech/cloudops-monitoring/300x250/index.html",
          "kb": 6.1
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/saas-tech/cloudops-monitoring/728x90/index.html",
          "kb": 6.3
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/saas-tech/cloudops-monitoring/160x600/index.html",
          "kb": 7.3
        }
      }
    },
    {
      "id": 6,
      "slug": "taskflow-ai",
      "title": "TaskFlow AI Productivity",
      "brand": "TaskFlow AI",
      "category": "saas-tech",
      "categoryLabel": "SaaS & Tech",
      "industry": "AI Productivity SaaS",
      "value": "Problem-to-solution storytelling that converts busy teams into free-trial users.",
      "keywords": [
        "saas",
        "ai",
        "productivity",
        "automation",
        "b2b"
      ],
      "cta": "Start Free Trial",
      "accent": "#818CF8",
      "border": "#333",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/saas-tech/taskflow-ai/300x250/index.html",
          "kb": 6.1
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/saas-tech/taskflow-ai/728x90/index.html",
          "kb": 6.3
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/saas-tech/taskflow-ai/160x600/index.html",
          "kb": 7.2
        }
      }
    },
    {
      "id": 7,
      "slug": "cybershield-endpoint",
      "title": "CyberShield Endpoint Defense",
      "brand": "CyberShield",
      "category": "saas-tech",
      "categoryLabel": "SaaS & Tech",
      "industry": "Cybersecurity",
      "value": "Enterprise demo-request campaign positioning zero-trust endpoint protection.",
      "keywords": [
        "saas",
        "security",
        "cyber",
        "enterprise",
        "b2b"
      ],
      "cta": "Get a Demo",
      "accent": "#22C55E",
      "border": "#333",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/saas-tech/cybershield-endpoint/300x250/index.html",
          "kb": 6
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/saas-tech/cybershield-endpoint/728x90/index.html",
          "kb": 6.2
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/saas-tech/cybershield-endpoint/160x600/index.html",
          "kb": 7.2
        }
      }
    },
    {
      "id": 8,
      "slug": "finflow-accounting",
      "title": "FinFlow Stripe Accounting",
      "brand": "FinFlow",
      "category": "saas-tech",
      "categoryLabel": "SaaS & Tech",
      "industry": "Fintech SaaS",
      "value": "Clean light-mode campaign selling automated Stripe reconciliation to founders.",
      "keywords": [
        "saas",
        "accounting",
        "stripe",
        "fintech",
        "startups"
      ],
      "cta": "Try It Free",
      "accent": "#635BFF",
      "border": "#e2e8f0",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/saas-tech/finflow-accounting/300x250/index.html",
          "kb": 5.9
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/saas-tech/finflow-accounting/728x90/index.html",
          "kb": 6.2
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/saas-tech/finflow-accounting/160x600/index.html",
          "kb": 7.1
        }
      }
    },
    {
      "id": 9,
      "slug": "the-grand-penthouse",
      "title": "The Grand Penthouse",
      "brand": "The Grand",
      "category": "real-estate",
      "categoryLabel": "Real Estate & Architecture",
      "industry": "Luxury Residential",
      "value": "Charcoal-and-gold prestige creative driving private viewing appointments.",
      "keywords": [
        "luxury",
        "real estate",
        "penthouse",
        "residential",
        "premium"
      ],
      "cta": "Book Private Tour",
      "accent": "#C9A45C",
      "border": "#333",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/real-estate/the-grand-penthouse/300x250/index.html",
          "kb": 5.9
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/real-estate/the-grand-penthouse/728x90/index.html",
          "kb": 6.1
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/real-estate/the-grand-penthouse/160x600/index.html",
          "kb": 7.1
        }
      }
    },
    {
      "id": 10,
      "slug": "azure-coastal-villas",
      "title": "Azure Coastal Villas",
      "brand": "Azure Coast",
      "category": "real-estate",
      "categoryLabel": "Real Estate & Architecture",
      "industry": "Resort Real Estate",
      "value": "Aspirational ocean-toned creative selling beachfront villa site visits.",
      "keywords": [
        "luxury",
        "real estate",
        "villa",
        "beach",
        "resort"
      ],
      "cta": "Reserve a Visit",
      "accent": "#FCD34D",
      "border": "#333",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/real-estate/azure-coastal-villas/300x250/index.html",
          "kb": 6.2
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/real-estate/azure-coastal-villas/728x90/index.html",
          "kb": 6.4
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/real-estate/azure-coastal-villas/160x600/index.html",
          "kb": 7.3
        }
      }
    },
    {
      "id": 11,
      "slug": "urban-loft-living",
      "title": "Urban Loft Living",
      "brand": "Foundry Lofts",
      "category": "real-estate",
      "categoryLabel": "Real Estate & Architecture",
      "industry": "Urban Rentals",
      "value": "Industrial-chic leasing campaign with a move-in incentive for young renters.",
      "keywords": [
        "real estate",
        "rental",
        "loft",
        "urban",
        "discount"
      ],
      "cta": "View Floor Plans",
      "accent": "#F97316",
      "border": "#333",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/real-estate/urban-loft-living/300x250/index.html",
          "kb": 6.1
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/real-estate/urban-loft-living/728x90/index.html",
          "kb": 5.9
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/real-estate/urban-loft-living/160x600/index.html",
          "kb": 7.3
        }
      }
    },
    {
      "id": 12,
      "slug": "skyline-commercial-hub",
      "title": "Skyline Commercial Hub",
      "brand": "Skyline Hub",
      "category": "real-estate",
      "categoryLabel": "Real Estate & Architecture",
      "industry": "Commercial Office",
      "value": "B2B leasing creative marketing Grade-A, sustainability-certified office floors.",
      "keywords": [
        "real estate",
        "commercial",
        "office",
        "b2b",
        "architecture"
      ],
      "cta": "Schedule a Tour",
      "accent": "#60A5FA",
      "border": "#333",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/real-estate/skyline-commercial-hub/300x250/index.html",
          "kb": 6.1
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/real-estate/skyline-commercial-hub/728x90/index.html",
          "kb": 6.3
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/real-estate/skyline-commercial-hub/160x600/index.html",
          "kb": 7.3
        }
      }
    },
    {
      "id": 13,
      "slug": "apex-prime-trading",
      "title": "Apex Prime Trading",
      "brand": "Apex Prime",
      "category": "finance-crypto",
      "categoryLabel": "Finance & Crypto",
      "industry": "Brokerage & Crypto",
      "value": "High-energy account-opening creative for a zero-commission trading platform.",
      "keywords": [
        "finance",
        "crypto",
        "trading",
        "stocks",
        "fintech"
      ],
      "cta": "Open Account",
      "accent": "#10B981",
      "border": "#333",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/finance-crypto/apex-prime-trading/300x250/index.html",
          "kb": 6.3
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/finance-crypto/apex-prime-trading/728x90/index.html",
          "kb": 6.1
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/finance-crypto/apex-prime-trading/160x600/index.html",
          "kb": 7.5
        }
      }
    },
    {
      "id": 14,
      "slug": "nova-digital-bank",
      "title": "Nova Digital Bank",
      "brand": "Nova",
      "category": "finance-crypto",
      "categoryLabel": "Finance & Crypto",
      "industry": "Neobank",
      "value": "Vibrant mobile-first acquisition ad for a fee-free digital bank account.",
      "keywords": [
        "finance",
        "bank",
        "fintech",
        "mobile",
        "neobank"
      ],
      "cta": "Get Nova Free",
      "accent": "#C084FC",
      "border": "#333",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/finance-crypto/nova-digital-bank/300x250/index.html",
          "kb": 6
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/finance-crypto/nova-digital-bank/728x90/index.html",
          "kb": 6.2
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/finance-crypto/nova-digital-bank/160x600/index.html",
          "kb": 7.2
        }
      }
    },
    {
      "id": 15,
      "slug": "wealthwise-mutual-funds",
      "title": "WealthWise Mutual Funds",
      "brand": "WealthWise",
      "category": "finance-crypto",
      "categoryLabel": "Finance & Crypto",
      "industry": "Asset Management",
      "value": "Trust-building light creative that lowers the barrier to first-time investing.",
      "keywords": [
        "finance",
        "investing",
        "mutual funds",
        "wealth",
        "sip"
      ],
      "cta": "Start Investing",
      "accent": "#16A34A",
      "border": "#e2e8f0",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/finance-crypto/wealthwise-mutual-funds/300x250/index.html",
          "kb": 5.8
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/finance-crypto/wealthwise-mutual-funds/728x90/index.html",
          "kb": 6
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/finance-crypto/wealthwise-mutual-funds/160x600/index.html",
          "kb": 7
        }
      }
    },
    {
      "id": 16,
      "slug": "safeguard-life-insurance",
      "title": "SafeGuard Life Insurance",
      "brand": "SafeGuard Life",
      "category": "finance-crypto",
      "categoryLabel": "Finance & Crypto",
      "industry": "Insurance",
      "value": "Reassuring family-protection message optimised for quick quote requests.",
      "keywords": [
        "finance",
        "insurance",
        "life",
        "family",
        "quote"
      ],
      "cta": "Get a Free Quote",
      "accent": "#0369A1",
      "border": "#e2e8f0",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/finance-crypto/safeguard-life-insurance/300x250/index.html",
          "kb": 6.1
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/finance-crypto/safeguard-life-insurance/728x90/index.html",
          "kb": 6.3
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/finance-crypto/safeguard-life-insurance/160x600/index.html",
          "kb": 7.3
        }
      }
    },
    {
      "id": 17,
      "slug": "pureglow-skincare",
      "title": "PureGlow Skincare",
      "brand": "PureGlow",
      "category": "healthcare-fitness",
      "categoryLabel": "Healthcare & Fitness",
      "industry": "Beauty & Wellness",
      "value": "Soft, premium beauty creative launching a clean vitamin C serum.",
      "keywords": [
        "beauty",
        "skincare",
        "wellness",
        "discount",
        "vegan"
      ],
      "cta": "Shop the Serum",
      "accent": "#DB2777",
      "border": "#e2e8f0",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/healthcare-fitness/pureglow-skincare/300x250/index.html",
          "kb": 6.2
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/healthcare-fitness/pureglow-skincare/728x90/index.html",
          "kb": 6
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/healthcare-fitness/pureglow-skincare/160x600/index.html",
          "kb": 7.4
        }
      }
    },
    {
      "id": 18,
      "slug": "fitpulse-smartwatch",
      "title": "FitPulse Gym Smartwatch",
      "brand": "FitPulse",
      "category": "healthcare-fitness",
      "categoryLabel": "Healthcare & Fitness",
      "industry": "Fitness Wearables",
      "value": "High-intensity product launch creative built around pre-order urgency.",
      "keywords": [
        "fitness",
        "health",
        "smartwatch",
        "wearable",
        "gym"
      ],
      "cta": "Pre-Order Now",
      "accent": "#EF4444",
      "border": "#333",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/healthcare-fitness/fitpulse-smartwatch/300x250/index.html",
          "kb": 6.4
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/healthcare-fitness/fitpulse-smartwatch/728x90/index.html",
          "kb": 6.2
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/healthcare-fitness/fitpulse-smartwatch/160x600/index.html",
          "kb": 7.6
        }
      }
    },
    {
      "id": 19,
      "slug": "dentalpro-clinics",
      "title": "DentalPro Modern Clinics",
      "brand": "DentalPro",
      "category": "healthcare-fitness",
      "categoryLabel": "Healthcare & Fitness",
      "industry": "Healthcare Clinics",
      "value": "Clinical, calming creative that drives new-patient appointment bookings.",
      "keywords": [
        "health",
        "dental",
        "clinic",
        "healthcare",
        "appointment"
      ],
      "cta": "Book Appointment",
      "accent": "#0891B2",
      "border": "#e2e8f0",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/healthcare-fitness/dentalpro-clinics/300x250/index.html",
          "kb": 6.5
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/healthcare-fitness/dentalpro-clinics/728x90/index.html",
          "kb": 6.3
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/healthcare-fitness/dentalpro-clinics/160x600/index.html",
          "kb": 7.7
        }
      }
    },
    {
      "id": 20,
      "slug": "nutrifuel-meal-prep",
      "title": "NutriFuel Meal Prep",
      "brand": "NutriFuel",
      "category": "healthcare-fitness",
      "categoryLabel": "Healthcare & Fitness",
      "industry": "Health Food Delivery",
      "value": "Fresh, energetic subscription offer for macro-balanced meal delivery.",
      "keywords": [
        "health",
        "fitness",
        "meal prep",
        "food",
        "discount"
      ],
      "cta": "Claim 50% Off",
      "accent": "#84CC16",
      "border": "#333",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/healthcare-fitness/nutrifuel-meal-prep/300x250/index.html",
          "kb": 6.4
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/healthcare-fitness/nutrifuel-meal-prep/728x90/index.html",
          "kb": 6.2
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/healthcare-fitness/nutrifuel-meal-prep/160x600/index.html",
          "kb": 7.6
        }
      }
    }
  ]
};
