/* Generated by tools/build-ads.mjs — edit campaigns there and re-run: node tools/build-ads.mjs */
window.ADSTUDIO = {
  "gsap": {
    "version": "3.12.2",
    "url": "https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.2/gsap.min.js",
    "kb": {
      "min": 69.8,
      "gzip": 27.1
    }
  },
  "clickTag": "https://www.google.com",
  "animation": {
    "loop": 6,
    "plays": 2,
    "pause": 1,
    "total": 13
  },
  "categories": [
    {
      "slug": "ecommerce-retail",
      "label": "E-Commerce & Retail"
    },
    {
      "slug": "saas-tech",
      "label": "SaaS & Tech"
    },
    {
      "slug": "real-estate",
      "label": "Real Estate & Architecture"
    },
    {
      "slug": "finance-crypto",
      "label": "Finance & Crypto"
    },
    {
      "slug": "healthcare-fitness",
      "label": "Healthcare & Fitness"
    }
  ],
  "styles": [
    {
      "slug": "classic",
      "label": "Classic Hero"
    },
    {
      "slug": "split",
      "label": "Split Panel"
    },
    {
      "slug": "kinetic",
      "label": "Kinetic Type"
    },
    {
      "slug": "cards",
      "label": "Card Stack"
    },
    {
      "slug": "data",
      "label": "Live Data Chart"
    },
    {
      "slug": "spotlight",
      "label": "Spotlight Burst"
    },
    {
      "slug": "ticker",
      "label": "Countdown Ticker"
    },
    {
      "slug": "editorial",
      "label": "Editorial Serif"
    },
    {
      "slug": "neon",
      "label": "Neon Glitch"
    },
    {
      "slug": "blob",
      "label": "Organic Blobs"
    }
  ],
  "campaigns": [
    {
      "id": 1,
      "slug": "sneaker-drop",
      "title": "Sneaker Drop",
      "brand": "Stride",
      "category": "ecommerce-retail",
      "categoryLabel": "E-Commerce & Retail",
      "style": "classic",
      "styleLabel": "Classic Hero",
      "industry": "Footwear Retail",
      "value": "Limited-edition runner launch driven by flash pricing and scarcity messaging.",
      "keywords": [
        "sneakers",
        "discount",
        "flash sale",
        "fashion",
        "retail"
      ],
      "cta": "Shop Now",
      "accent": "#FF3D5A",
      "border": "#333",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/ecommerce-retail/sneaker-drop/300x250/index.html",
          "kb": 6.2
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/ecommerce-retail/sneaker-drop/728x90/index.html",
          "kb": 6
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/ecommerce-retail/sneaker-drop/160x600/index.html",
          "kb": 7.4
        }
      }
    },
    {
      "id": 2,
      "slug": "cyber-monday-gadgets",
      "title": "Cyber Monday Gadgets",
      "brand": "Voltix",
      "category": "ecommerce-retail",
      "categoryLabel": "E-Commerce & Retail",
      "style": "classic",
      "styleLabel": "Classic Hero",
      "industry": "Consumer Electronics",
      "value": "Doorbuster electronics event with bold neon styling and deep-discount hooks.",
      "keywords": [
        "cyber monday",
        "discount",
        "electronics",
        "gadgets",
        "deals"
      ],
      "cta": "Grab the Deal",
      "accent": "#22D3EE",
      "border": "#333",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/ecommerce-retail/cyber-monday-gadgets/300x250/index.html",
          "kb": 6.2
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/ecommerce-retail/cyber-monday-gadgets/728x90/index.html",
          "kb": 6.1
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/ecommerce-retail/cyber-monday-gadgets/160x600/index.html",
          "kb": 7.4
        }
      }
    },
    {
      "id": 3,
      "slug": "luxury-fashion-autumn",
      "title": "Luxury Fashion Autumn",
      "brand": "Maison Aurèle",
      "category": "ecommerce-retail",
      "categoryLabel": "E-Commerce & Retail",
      "style": "classic",
      "styleLabel": "Classic Hero",
      "industry": "Luxury Apparel",
      "value": "Editorial, serif-led seasonal campaign for a premium cashmere collection.",
      "keywords": [
        "luxury",
        "fashion",
        "autumn",
        "apparel",
        "premium"
      ],
      "cta": "Discover Now",
      "accent": "#8C5A3C",
      "border": "#e2e8f0",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/ecommerce-retail/luxury-fashion-autumn/300x250/index.html",
          "kb": 5.7
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/ecommerce-retail/luxury-fashion-autumn/728x90/index.html",
          "kb": 5.9
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/ecommerce-retail/luxury-fashion-autumn/160x600/index.html",
          "kb": 6.9
        }
      }
    },
    {
      "id": 4,
      "slug": "organic-coffee-roasters",
      "title": "Organic Coffee Roasters",
      "brand": "Ember & Oak",
      "category": "ecommerce-retail",
      "categoryLabel": "E-Commerce & Retail",
      "style": "classic",
      "styleLabel": "Classic Hero",
      "industry": "Food & Beverage D2C",
      "value": "Warm, craft-led subscription offer for fresh-roasted single-origin beans.",
      "keywords": [
        "coffee",
        "organic",
        "subscription",
        "discount",
        "d2c"
      ],
      "cta": "Order Fresh",
      "accent": "#E0A96D",
      "border": "#333",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/ecommerce-retail/organic-coffee-roasters/300x250/index.html",
          "kb": 6.3
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/ecommerce-retail/organic-coffee-roasters/728x90/index.html",
          "kb": 6.1
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/ecommerce-retail/organic-coffee-roasters/160x600/index.html",
          "kb": 7.5
        }
      }
    },
    {
      "id": 5,
      "slug": "cloudops-monitoring",
      "title": "CloudOps Monitoring",
      "brand": "CloudOps",
      "category": "saas-tech",
      "categoryLabel": "SaaS & Tech",
      "style": "classic",
      "styleLabel": "Classic Hero",
      "industry": "DevOps SaaS",
      "value": "Developer-focused trial acquisition for a full-stack observability platform.",
      "keywords": [
        "saas",
        "monitoring",
        "devops",
        "cloud",
        "b2b"
      ],
      "cta": "Start Free Trial",
      "accent": "#34D399",
      "border": "#333",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/saas-tech/cloudops-monitoring/300x250/index.html",
          "kb": 6.1
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/saas-tech/cloudops-monitoring/728x90/index.html",
          "kb": 6.3
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/saas-tech/cloudops-monitoring/160x600/index.html",
          "kb": 7.3
        }
      }
    },
    {
      "id": 6,
      "slug": "taskflow-ai",
      "title": "TaskFlow AI Productivity",
      "brand": "TaskFlow AI",
      "category": "saas-tech",
      "categoryLabel": "SaaS & Tech",
      "style": "classic",
      "styleLabel": "Classic Hero",
      "industry": "AI Productivity SaaS",
      "value": "Problem-to-solution storytelling that converts busy teams into free-trial users.",
      "keywords": [
        "saas",
        "ai",
        "productivity",
        "automation",
        "b2b"
      ],
      "cta": "Start Free Trial",
      "accent": "#818CF8",
      "border": "#333",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/saas-tech/taskflow-ai/300x250/index.html",
          "kb": 6.1
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/saas-tech/taskflow-ai/728x90/index.html",
          "kb": 6.3
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/saas-tech/taskflow-ai/160x600/index.html",
          "kb": 7.2
        }
      }
    },
    {
      "id": 7,
      "slug": "cybershield-endpoint",
      "title": "CyberShield Endpoint Defense",
      "brand": "CyberShield",
      "category": "saas-tech",
      "categoryLabel": "SaaS & Tech",
      "style": "classic",
      "styleLabel": "Classic Hero",
      "industry": "Cybersecurity",
      "value": "Enterprise demo-request campaign positioning zero-trust endpoint protection.",
      "keywords": [
        "saas",
        "security",
        "cyber",
        "enterprise",
        "b2b"
      ],
      "cta": "Get a Demo",
      "accent": "#22C55E",
      "border": "#333",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/saas-tech/cybershield-endpoint/300x250/index.html",
          "kb": 6
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/saas-tech/cybershield-endpoint/728x90/index.html",
          "kb": 6.2
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/saas-tech/cybershield-endpoint/160x600/index.html",
          "kb": 7.2
        }
      }
    },
    {
      "id": 8,
      "slug": "finflow-accounting",
      "title": "FinFlow Stripe Accounting",
      "brand": "FinFlow",
      "category": "saas-tech",
      "categoryLabel": "SaaS & Tech",
      "style": "classic",
      "styleLabel": "Classic Hero",
      "industry": "Fintech SaaS",
      "value": "Clean light-mode campaign selling automated Stripe reconciliation to founders.",
      "keywords": [
        "saas",
        "accounting",
        "stripe",
        "fintech",
        "startups"
      ],
      "cta": "Try It Free",
      "accent": "#635BFF",
      "border": "#e2e8f0",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/saas-tech/finflow-accounting/300x250/index.html",
          "kb": 5.9
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/saas-tech/finflow-accounting/728x90/index.html",
          "kb": 6.2
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/saas-tech/finflow-accounting/160x600/index.html",
          "kb": 7.1
        }
      }
    },
    {
      "id": 9,
      "slug": "the-grand-penthouse",
      "title": "The Grand Penthouse",
      "brand": "The Grand",
      "category": "real-estate",
      "categoryLabel": "Real Estate & Architecture",
      "style": "classic",
      "styleLabel": "Classic Hero",
      "industry": "Luxury Residential",
      "value": "Charcoal-and-gold prestige creative driving private viewing appointments.",
      "keywords": [
        "luxury",
        "real estate",
        "penthouse",
        "residential",
        "premium"
      ],
      "cta": "Book Private Tour",
      "accent": "#C9A45C",
      "border": "#333",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/real-estate/the-grand-penthouse/300x250/index.html",
          "kb": 5.9
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/real-estate/the-grand-penthouse/728x90/index.html",
          "kb": 6.1
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/real-estate/the-grand-penthouse/160x600/index.html",
          "kb": 7.1
        }
      }
    },
    {
      "id": 10,
      "slug": "azure-coastal-villas",
      "title": "Azure Coastal Villas",
      "brand": "Azure Coast",
      "category": "real-estate",
      "categoryLabel": "Real Estate & Architecture",
      "style": "classic",
      "styleLabel": "Classic Hero",
      "industry": "Resort Real Estate",
      "value": "Aspirational ocean-toned creative selling beachfront villa site visits.",
      "keywords": [
        "luxury",
        "real estate",
        "villa",
        "beach",
        "resort"
      ],
      "cta": "Reserve a Visit",
      "accent": "#FCD34D",
      "border": "#333",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/real-estate/azure-coastal-villas/300x250/index.html",
          "kb": 6.2
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/real-estate/azure-coastal-villas/728x90/index.html",
          "kb": 6.4
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/real-estate/azure-coastal-villas/160x600/index.html",
          "kb": 7.3
        }
      }
    },
    {
      "id": 11,
      "slug": "urban-loft-living",
      "title": "Urban Loft Living",
      "brand": "Foundry Lofts",
      "category": "real-estate",
      "categoryLabel": "Real Estate & Architecture",
      "style": "classic",
      "styleLabel": "Classic Hero",
      "industry": "Urban Rentals",
      "value": "Industrial-chic leasing campaign with a move-in incentive for young renters.",
      "keywords": [
        "real estate",
        "rental",
        "loft",
        "urban",
        "discount"
      ],
      "cta": "View Floor Plans",
      "accent": "#F97316",
      "border": "#333",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/real-estate/urban-loft-living/300x250/index.html",
          "kb": 6.1
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/real-estate/urban-loft-living/728x90/index.html",
          "kb": 5.9
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/real-estate/urban-loft-living/160x600/index.html",
          "kb": 7.3
        }
      }
    },
    {
      "id": 12,
      "slug": "skyline-commercial-hub",
      "title": "Skyline Commercial Hub",
      "brand": "Skyline Hub",
      "category": "real-estate",
      "categoryLabel": "Real Estate & Architecture",
      "style": "classic",
      "styleLabel": "Classic Hero",
      "industry": "Commercial Office",
      "value": "B2B leasing creative marketing Grade-A, sustainability-certified office floors.",
      "keywords": [
        "real estate",
        "commercial",
        "office",
        "b2b",
        "architecture"
      ],
      "cta": "Schedule a Tour",
      "accent": "#60A5FA",
      "border": "#333",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/real-estate/skyline-commercial-hub/300x250/index.html",
          "kb": 6.1
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/real-estate/skyline-commercial-hub/728x90/index.html",
          "kb": 6.3
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/real-estate/skyline-commercial-hub/160x600/index.html",
          "kb": 7.3
        }
      }
    },
    {
      "id": 13,
      "slug": "apex-prime-trading",
      "title": "Apex Prime Trading",
      "brand": "Apex Prime",
      "category": "finance-crypto",
      "categoryLabel": "Finance & Crypto",
      "style": "classic",
      "styleLabel": "Classic Hero",
      "industry": "Brokerage & Crypto",
      "value": "High-energy account-opening creative for a zero-commission trading platform.",
      "keywords": [
        "finance",
        "crypto",
        "trading",
        "stocks",
        "fintech"
      ],
      "cta": "Open Account",
      "accent": "#10B981",
      "border": "#333",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/finance-crypto/apex-prime-trading/300x250/index.html",
          "kb": 6.3
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/finance-crypto/apex-prime-trading/728x90/index.html",
          "kb": 6.1
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/finance-crypto/apex-prime-trading/160x600/index.html",
          "kb": 7.5
        }
      }
    },
    {
      "id": 14,
      "slug": "nova-digital-bank",
      "title": "Nova Digital Bank",
      "brand": "Nova",
      "category": "finance-crypto",
      "categoryLabel": "Finance & Crypto",
      "style": "classic",
      "styleLabel": "Classic Hero",
      "industry": "Neobank",
      "value": "Vibrant mobile-first acquisition ad for a fee-free digital bank account.",
      "keywords": [
        "finance",
        "bank",
        "fintech",
        "mobile",
        "neobank"
      ],
      "cta": "Get Nova Free",
      "accent": "#C084FC",
      "border": "#333",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/finance-crypto/nova-digital-bank/300x250/index.html",
          "kb": 6
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/finance-crypto/nova-digital-bank/728x90/index.html",
          "kb": 6.2
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/finance-crypto/nova-digital-bank/160x600/index.html",
          "kb": 7.2
        }
      }
    },
    {
      "id": 15,
      "slug": "wealthwise-mutual-funds",
      "title": "WealthWise Mutual Funds",
      "brand": "WealthWise",
      "category": "finance-crypto",
      "categoryLabel": "Finance & Crypto",
      "style": "classic",
      "styleLabel": "Classic Hero",
      "industry": "Asset Management",
      "value": "Trust-building light creative that lowers the barrier to first-time investing.",
      "keywords": [
        "finance",
        "investing",
        "mutual funds",
        "wealth",
        "sip"
      ],
      "cta": "Start Investing",
      "accent": "#16A34A",
      "border": "#e2e8f0",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/finance-crypto/wealthwise-mutual-funds/300x250/index.html",
          "kb": 5.8
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/finance-crypto/wealthwise-mutual-funds/728x90/index.html",
          "kb": 6
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/finance-crypto/wealthwise-mutual-funds/160x600/index.html",
          "kb": 7
        }
      }
    },
    {
      "id": 16,
      "slug": "safeguard-life-insurance",
      "title": "SafeGuard Life Insurance",
      "brand": "SafeGuard Life",
      "category": "finance-crypto",
      "categoryLabel": "Finance & Crypto",
      "style": "classic",
      "styleLabel": "Classic Hero",
      "industry": "Insurance",
      "value": "Reassuring family-protection message optimised for quick quote requests.",
      "keywords": [
        "finance",
        "insurance",
        "life",
        "family",
        "quote"
      ],
      "cta": "Get a Free Quote",
      "accent": "#0369A1",
      "border": "#e2e8f0",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/finance-crypto/safeguard-life-insurance/300x250/index.html",
          "kb": 6.1
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/finance-crypto/safeguard-life-insurance/728x90/index.html",
          "kb": 6.3
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/finance-crypto/safeguard-life-insurance/160x600/index.html",
          "kb": 7.3
        }
      }
    },
    {
      "id": 17,
      "slug": "pureglow-skincare",
      "title": "PureGlow Skincare",
      "brand": "PureGlow",
      "category": "healthcare-fitness",
      "categoryLabel": "Healthcare & Fitness",
      "style": "classic",
      "styleLabel": "Classic Hero",
      "industry": "Beauty & Wellness",
      "value": "Soft, premium beauty creative launching a clean vitamin C serum.",
      "keywords": [
        "beauty",
        "skincare",
        "wellness",
        "discount",
        "vegan"
      ],
      "cta": "Shop the Serum",
      "accent": "#DB2777",
      "border": "#e2e8f0",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/healthcare-fitness/pureglow-skincare/300x250/index.html",
          "kb": 6.2
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/healthcare-fitness/pureglow-skincare/728x90/index.html",
          "kb": 6
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/healthcare-fitness/pureglow-skincare/160x600/index.html",
          "kb": 7.4
        }
      }
    },
    {
      "id": 18,
      "slug": "fitpulse-smartwatch",
      "title": "FitPulse Gym Smartwatch",
      "brand": "FitPulse",
      "category": "healthcare-fitness",
      "categoryLabel": "Healthcare & Fitness",
      "style": "classic",
      "styleLabel": "Classic Hero",
      "industry": "Fitness Wearables",
      "value": "High-intensity product launch creative built around pre-order urgency.",
      "keywords": [
        "fitness",
        "health",
        "smartwatch",
        "wearable",
        "gym"
      ],
      "cta": "Pre-Order Now",
      "accent": "#EF4444",
      "border": "#333",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/healthcare-fitness/fitpulse-smartwatch/300x250/index.html",
          "kb": 6.4
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/healthcare-fitness/fitpulse-smartwatch/728x90/index.html",
          "kb": 6.2
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/healthcare-fitness/fitpulse-smartwatch/160x600/index.html",
          "kb": 7.6
        }
      }
    },
    {
      "id": 19,
      "slug": "dentalpro-clinics",
      "title": "DentalPro Modern Clinics",
      "brand": "DentalPro",
      "category": "healthcare-fitness",
      "categoryLabel": "Healthcare & Fitness",
      "style": "classic",
      "styleLabel": "Classic Hero",
      "industry": "Healthcare Clinics",
      "value": "Clinical, calming creative that drives new-patient appointment bookings.",
      "keywords": [
        "health",
        "dental",
        "clinic",
        "healthcare",
        "appointment"
      ],
      "cta": "Book Appointment",
      "accent": "#0891B2",
      "border": "#e2e8f0",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/healthcare-fitness/dentalpro-clinics/300x250/index.html",
          "kb": 6.5
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/healthcare-fitness/dentalpro-clinics/728x90/index.html",
          "kb": 6.3
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/healthcare-fitness/dentalpro-clinics/160x600/index.html",
          "kb": 7.7
        }
      }
    },
    {
      "id": 20,
      "slug": "nutrifuel-meal-prep",
      "title": "NutriFuel Meal Prep",
      "brand": "NutriFuel",
      "category": "healthcare-fitness",
      "categoryLabel": "Healthcare & Fitness",
      "style": "classic",
      "styleLabel": "Classic Hero",
      "industry": "Health Food Delivery",
      "value": "Fresh, energetic subscription offer for macro-balanced meal delivery.",
      "keywords": [
        "health",
        "fitness",
        "meal prep",
        "food",
        "discount"
      ],
      "cta": "Claim 50% Off",
      "accent": "#84CC16",
      "border": "#333",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/healthcare-fitness/nutrifuel-meal-prep/300x250/index.html",
          "kb": 6.4
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/healthcare-fitness/nutrifuel-meal-prep/728x90/index.html",
          "kb": 6.2
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/healthcare-fitness/nutrifuel-meal-prep/160x600/index.html",
          "kb": 7.6
        }
      }
    },
    {
      "id": 21,
      "slug": "hygge-home-furniture",
      "title": "Nordic Home Furniture",
      "brand": "Hygge & Co.",
      "category": "ecommerce-retail",
      "categoryLabel": "E-Commerce & Retail",
      "style": "editorial",
      "styleLabel": "Editorial Serif",
      "industry": "Home & Furniture",
      "value": "Calm, magazine-style creative for handcrafted Scandinavian furniture.",
      "keywords": [
        "furniture",
        "home",
        "interior",
        "scandinavian",
        "luxury"
      ],
      "cta": "Shop Collection",
      "accent": "#5F7A61",
      "border": "#e2e8f0",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/ecommerce-retail/hygge-home-furniture/300x250/index.html",
          "kb": 4.8
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/ecommerce-retail/hygge-home-furniture/728x90/index.html",
          "kb": 4.7
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/ecommerce-retail/hygge-home-furniture/160x600/index.html",
          "kb": 5
        }
      }
    },
    {
      "id": 22,
      "slug": "datapulse-analytics",
      "title": "DataPulse Analytics",
      "brand": "DataPulse",
      "category": "saas-tech",
      "categoryLabel": "SaaS & Tech",
      "style": "data",
      "styleLabel": "Live Data Chart",
      "industry": "Analytics SaaS",
      "value": "Live-drawing chart creative that proves speed-to-insight in seconds.",
      "keywords": [
        "saas",
        "analytics",
        "data",
        "dashboards",
        "b2b"
      ],
      "cta": "Start Free Trial",
      "accent": "#F472B6",
      "border": "#333",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/saas-tech/datapulse-analytics/300x250/index.html",
          "kb": 5.2
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/saas-tech/datapulse-analytics/728x90/index.html",
          "kb": 5.6
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/saas-tech/datapulse-analytics/160x600/index.html",
          "kb": 6.4
        }
      }
    },
    {
      "id": 23,
      "slug": "verde-eco-homes",
      "title": "Verde Eco Homes",
      "brand": "Verde Homes",
      "category": "real-estate",
      "categoryLabel": "Real Estate & Architecture",
      "style": "blob",
      "styleLabel": "Organic Blobs",
      "industry": "Sustainable Housing",
      "value": "Organic, nature-toned creative for net-zero family homes.",
      "keywords": [
        "real estate",
        "eco",
        "homes",
        "sustainable",
        "family"
      ],
      "cta": "Tour Show Home",
      "accent": "#16A34A",
      "border": "#e2e8f0",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/real-estate/verde-eco-homes/300x250/index.html",
          "kb": 5.2
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/real-estate/verde-eco-homes/728x90/index.html",
          "kb": 5.3
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/real-estate/verde-eco-homes/160x600/index.html",
          "kb": 6.1
        }
      }
    },
    {
      "id": 24,
      "slug": "bitvault-wallet",
      "title": "BitVault Crypto Wallet",
      "brand": "BitVault",
      "category": "finance-crypto",
      "categoryLabel": "Finance & Crypto",
      "style": "neon",
      "styleLabel": "Neon Glitch",
      "industry": "Crypto Custody",
      "value": "High-voltage neon creative for a self-custody crypto wallet.",
      "keywords": [
        "crypto",
        "bitcoin",
        "wallet",
        "security",
        "web3"
      ],
      "cta": "Get BitVault",
      "accent": "#F7931A",
      "border": "#333",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/finance-crypto/bitvault-wallet/300x250/index.html",
          "kb": 6.3
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/finance-crypto/bitvault-wallet/728x90/index.html",
          "kb": 6.2
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/finance-crypto/bitvault-wallet/160x600/index.html",
          "kb": 7.2
        }
      }
    },
    {
      "id": 25,
      "slug": "zenflow-yoga",
      "title": "ZenFlow Yoga Studio",
      "brand": "ZenFlow",
      "category": "healthcare-fitness",
      "categoryLabel": "Healthcare & Fitness",
      "style": "blob",
      "styleLabel": "Organic Blobs",
      "industry": "Yoga & Wellness",
      "value": "Calm, organic creative that invites beginners to a first free class.",
      "keywords": [
        "health",
        "yoga",
        "fitness",
        "wellness",
        "free"
      ],
      "cta": "Book a Class",
      "accent": "#6B8F5E",
      "border": "#e2e8f0",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/healthcare-fitness/zenflow-yoga/300x250/index.html",
          "kb": 5.9
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/healthcare-fitness/zenflow-yoga/728x90/index.html",
          "kb": 6
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/healthcare-fitness/zenflow-yoga/160x600/index.html",
          "kb": 6.9
        }
      }
    },
    {
      "id": 26,
      "slug": "pxl-gaming-gear",
      "title": "Pixel Arcade Gaming Gear",
      "brand": "PXL Gear",
      "category": "ecommerce-retail",
      "categoryLabel": "E-Commerce & Retail",
      "style": "neon",
      "styleLabel": "Neon Glitch",
      "industry": "Gaming Peripherals",
      "value": "Glitchy neon creative built to stop gamers mid-scroll.",
      "keywords": [
        "gaming",
        "esports",
        "discount",
        "neon",
        "gear"
      ],
      "cta": "Level Up Now",
      "accent": "#FF2BD6",
      "border": "#333",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/ecommerce-retail/pxl-gaming-gear/300x250/index.html",
          "kb": 6.3
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/ecommerce-retail/pxl-gaming-gear/728x90/index.html",
          "kb": 6.3
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/ecommerce-retail/pxl-gaming-gear/160x600/index.html",
          "kb": 7.2
        }
      }
    },
    {
      "id": 27,
      "slug": "codenest-deploy",
      "title": "CodeNest Dev Platform",
      "brand": "CodeNest",
      "category": "saas-tech",
      "categoryLabel": "SaaS & Tech",
      "style": "neon",
      "styleLabel": "Neon Glitch",
      "industry": "Developer Tools",
      "value": "Terminal-green neon creative for a one-click deployment platform.",
      "keywords": [
        "saas",
        "developer",
        "devops",
        "cloud",
        "deploy"
      ],
      "cta": "Deploy Free",
      "accent": "#22C55E",
      "border": "#333",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/saas-tech/codenest-deploy/300x250/index.html",
          "kb": 6
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/saas-tech/codenest-deploy/728x90/index.html",
          "kb": 6
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/saas-tech/codenest-deploy/160x600/index.html",
          "kb": 7
        }
      }
    },
    {
      "id": 28,
      "slug": "marina-bay-towers",
      "title": "Marina Bay Towers",
      "brand": "Marina Towers",
      "category": "real-estate",
      "categoryLabel": "Real Estate & Architecture",
      "style": "data",
      "styleLabel": "Live Data Chart",
      "industry": "Investment Property",
      "value": "Yield-chart creative that speaks directly to property investors.",
      "keywords": [
        "real estate",
        "investment",
        "waterfront",
        "condos",
        "yield"
      ],
      "cta": "Get Brochure",
      "accent": "#2DD4BF",
      "border": "#333",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/real-estate/marina-bay-towers/300x250/index.html",
          "kb": 5.4
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/real-estate/marina-bay-towers/728x90/index.html",
          "kb": 5.8
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/real-estate/marina-bay-towers/160x600/index.html",
          "kb": 6.5
        }
      }
    },
    {
      "id": 29,
      "slug": "roundup-investing",
      "title": "RoundUp Micro-Investing",
      "brand": "RoundUp",
      "category": "finance-crypto",
      "categoryLabel": "Finance & Crypto",
      "style": "data",
      "styleLabel": "Live Data Chart",
      "industry": "Micro-Investing",
      "value": "Count-up savings creative that makes spare change feel significant.",
      "keywords": [
        "finance",
        "investing",
        "savings",
        "fintech",
        "app"
      ],
      "cta": "Start Saving",
      "accent": "#0D9488",
      "border": "#e2e8f0",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/finance-crypto/roundup-investing/300x250/index.html",
          "kb": 5.1
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/finance-crypto/roundup-investing/728x90/index.html",
          "kb": 5.5
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/finance-crypto/roundup-investing/160x600/index.html",
          "kb": 6.3
        }
      }
    },
    {
      "id": 30,
      "slug": "ironcore-gym",
      "title": "IronCore Gym",
      "brand": "IronCore",
      "category": "healthcare-fitness",
      "categoryLabel": "Healthcare & Fitness",
      "style": "kinetic",
      "styleLabel": "Kinetic Type",
      "industry": "Gyms & Fitness",
      "value": "Aggressive kinetic type built for a gym membership push.",
      "keywords": [
        "fitness",
        "gym",
        "workout",
        "discount",
        "membership"
      ],
      "cta": "Join Now",
      "accent": "#EAB308",
      "border": "#333",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/healthcare-fitness/ironcore-gym/300x250/index.html",
          "kb": 4.9
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/healthcare-fitness/ironcore-gym/728x90/index.html",
          "kb": 5
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/healthcare-fitness/ironcore-gym/160x600/index.html",
          "kb": 5.1
        }
      }
    },
    {
      "id": 31,
      "slug": "bloomly-flowers",
      "title": "Bloom Flower Delivery",
      "brand": "Bloomly",
      "category": "ecommerce-retail",
      "categoryLabel": "E-Commerce & Retail",
      "style": "blob",
      "styleLabel": "Organic Blobs",
      "industry": "Gifting & Florals",
      "value": "Soft organic shapes for a same-day flower delivery offer.",
      "keywords": [
        "flowers",
        "gifting",
        "delivery",
        "discount",
        "florist"
      ],
      "cta": "Send Flowers",
      "accent": "#EC4899",
      "border": "#e2e8f0",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/ecommerce-retail/bloomly-flowers/300x250/index.html",
          "kb": 6
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/ecommerce-retail/bloomly-flowers/728x90/index.html",
          "kb": 6.1
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/ecommerce-retail/bloomly-flowers/160x600/index.html",
          "kb": 7
        }
      }
    },
    {
      "id": 32,
      "slug": "meetspace-video",
      "title": "MeetSpace Video",
      "brand": "MeetSpace",
      "category": "saas-tech",
      "categoryLabel": "SaaS & Tech",
      "style": "cards",
      "styleLabel": "Card Stack",
      "industry": "Collaboration SaaS",
      "value": "Clean light card-stack creative listing video-call features.",
      "keywords": [
        "saas",
        "video",
        "meetings",
        "remote",
        "collaboration"
      ],
      "cta": "Start a Meeting",
      "accent": "#0EA5E9",
      "border": "#e2e8f0",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/saas-tech/meetspace-video/300x250/index.html",
          "kb": 5.3
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/saas-tech/meetspace-video/728x90/index.html",
          "kb": 5
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/saas-tech/meetspace-video/160x600/index.html",
          "kb": 5.6
        }
      }
    },
    {
      "id": 33,
      "slug": "atelier-nord-architects",
      "title": "Atelier Nord Architects",
      "brand": "Atelier Nord",
      "category": "real-estate",
      "categoryLabel": "Real Estate & Architecture",
      "style": "editorial",
      "styleLabel": "Editorial Serif",
      "industry": "Architecture Studio",
      "value": "Magazine-grade editorial creative for an architecture practice.",
      "keywords": [
        "architecture",
        "design",
        "studio",
        "luxury",
        "commercial"
      ],
      "cta": "View Portfolio",
      "accent": "#B45309",
      "border": "#e2e8f0",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/real-estate/atelier-nord-architects/300x250/index.html",
          "kb": 4.7
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/real-estate/atelier-nord-architects/728x90/index.html",
          "kb": 4.6
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/real-estate/atelier-nord-architects/160x600/index.html",
          "kb": 4.9
        }
      }
    },
    {
      "id": 34,
      "slug": "loanleaf-mortgages",
      "title": "LoanLeaf Mortgages",
      "brand": "LoanLeaf",
      "category": "finance-crypto",
      "categoryLabel": "Finance & Crypto",
      "style": "blob",
      "styleLabel": "Organic Blobs",
      "industry": "Mortgage Lending",
      "value": "Friendly, organic creative that softens a mortgage rate message.",
      "keywords": [
        "finance",
        "mortgage",
        "home loan",
        "rates",
        "property"
      ],
      "cta": "Check My Rate",
      "accent": "#65A30D",
      "border": "#e2e8f0",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/finance-crypto/loanleaf-mortgages/300x250/index.html",
          "kb": 5.3
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/finance-crypto/loanleaf-mortgages/728x90/index.html",
          "kb": 5.4
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/finance-crypto/loanleaf-mortgages/160x600/index.html",
          "kb": 6.3
        }
      }
    },
    {
      "id": 35,
      "slug": "mindease-therapy",
      "title": "MindEase Therapy",
      "brand": "MindEase",
      "category": "healthcare-fitness",
      "categoryLabel": "Healthcare & Fitness",
      "style": "editorial",
      "styleLabel": "Editorial Serif",
      "industry": "Mental Health",
      "value": "Gentle editorial creative that lowers the barrier to starting therapy.",
      "keywords": [
        "health",
        "therapy",
        "mental health",
        "wellness",
        "online"
      ],
      "cta": "Get Matched",
      "accent": "#6D28D9",
      "border": "#e2e8f0",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/healthcare-fitness/mindease-therapy/300x250/index.html",
          "kb": 5.1
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/healthcare-fitness/mindease-therapy/728x90/index.html",
          "kb": 5
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/healthcare-fitness/mindease-therapy/160x600/index.html",
          "kb": 5.3
        }
      }
    },
    {
      "id": 36,
      "slug": "mercato-weekend-sale",
      "title": "Mega Weekend Sale",
      "brand": "Mercato",
      "category": "ecommerce-retail",
      "categoryLabel": "E-Commerce & Retail",
      "style": "ticker",
      "styleLabel": "Countdown Ticker",
      "industry": "Department Store",
      "value": "Urgency-first ticker creative with a live countdown for a 48-hour sale.",
      "keywords": [
        "sale",
        "discount",
        "weekend",
        "fashion",
        "urgency"
      ],
      "cta": "Shop the Sale",
      "accent": "#FACC15",
      "border": "#333",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/ecommerce-retail/mercato-weekend-sale/300x250/index.html",
          "kb": 6.4
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/ecommerce-retail/mercato-weekend-sale/728x90/index.html",
          "kb": 6.7
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/ecommerce-retail/mercato-weekend-sale/160x600/index.html",
          "kb": 7
        }
      }
    },
    {
      "id": 37,
      "slug": "inboxzero-ai",
      "title": "InboxZero Email AI",
      "brand": "InboxZero",
      "category": "saas-tech",
      "categoryLabel": "SaaS & Tech",
      "style": "kinetic",
      "styleLabel": "Kinetic Type",
      "industry": "AI Email Assistant",
      "value": "Kinetic type creative that makes inbox overload feel instantly solvable.",
      "keywords": [
        "saas",
        "ai",
        "email",
        "productivity",
        "automation"
      ],
      "cta": "Try It Free",
      "accent": "#FBBF24",
      "border": "#333",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/saas-tech/inboxzero-ai/300x250/index.html",
          "kb": 4.8
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/saas-tech/inboxzero-ai/728x90/index.html",
          "kb": 4.9
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/saas-tech/inboxzero-ai/160x600/index.html",
          "kb": 4.9
        }
      }
    },
    {
      "id": 38,
      "slug": "summit-ski-chalets",
      "title": "Summit Ski Chalets",
      "brand": "Summit Chalets",
      "category": "real-estate",
      "categoryLabel": "Real Estate & Architecture",
      "style": "split",
      "styleLabel": "Split Panel",
      "industry": "Alpine Resort Homes",
      "value": "Cold-toned split creative for ski-in, ski-out chalet stays.",
      "keywords": [
        "real estate",
        "ski",
        "chalet",
        "luxury",
        "vacation"
      ],
      "cta": "Reserve a Chalet",
      "accent": "#38BDF8",
      "border": "#333",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/real-estate/summit-ski-chalets/300x250/index.html",
          "kb": 4.4
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/real-estate/summit-ski-chalets/728x90/index.html",
          "kb": 4.6
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/real-estate/summit-ski-chalets/160x600/index.html",
          "kb": 5.3
        }
      }
    },
    {
      "id": 39,
      "slug": "stellar-credit-card",
      "title": "Stellar Credit Card",
      "brand": "Stellar",
      "category": "finance-crypto",
      "categoryLabel": "Finance & Crypto",
      "style": "spotlight",
      "styleLabel": "Spotlight Burst",
      "industry": "Credit Cards",
      "value": "Premium spotlight creative that makes a metal card feel like a trophy.",
      "keywords": [
        "finance",
        "credit card",
        "cashback",
        "rewards",
        "premium"
      ],
      "cta": "Apply Now",
      "accent": "#C7D2FE",
      "border": "#333",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/finance-crypto/stellar-credit-card/300x250/index.html",
          "kb": 5.4
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/finance-crypto/stellar-credit-card/728x90/index.html",
          "kb": 5.5
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/finance-crypto/stellar-credit-card/160x600/index.html",
          "kb": 6.5
        }
      }
    },
    {
      "id": 40,
      "slug": "hydrapure-bottle",
      "title": "HydraPure Smart Bottle",
      "brand": "HydraPure",
      "category": "healthcare-fitness",
      "categoryLabel": "Healthcare & Fitness",
      "style": "spotlight",
      "styleLabel": "Spotlight Burst",
      "industry": "Health Tech",
      "value": "Spotlit product-hero creative for a self-cleaning bottle.",
      "keywords": [
        "health",
        "hydration",
        "gadgets",
        "discount",
        "wellness"
      ],
      "cta": "Shop HydraPure",
      "accent": "#38BDF8",
      "border": "#333",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/healthcare-fitness/hydrapure-bottle/300x250/index.html",
          "kb": 5.9
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/healthcare-fitness/hydrapure-bottle/728x90/index.html",
          "kb": 6
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/healthcare-fitness/hydrapure-bottle/160x600/index.html",
          "kb": 7
        }
      }
    },
    {
      "id": 41,
      "slug": "aurum-fine-jewelry",
      "title": "Aurum Fine Jewelry",
      "brand": "Aurum",
      "category": "ecommerce-retail",
      "categoryLabel": "E-Commerce & Retail",
      "style": "spotlight",
      "styleLabel": "Spotlight Burst",
      "industry": "Fine Jewelry",
      "value": "Jewel-box spotlight with light rays for a luxury gold collection.",
      "keywords": [
        "luxury",
        "jewelry",
        "gold",
        "diamonds",
        "gifting"
      ],
      "cta": "Explore Pieces",
      "accent": "#D4AF37",
      "border": "#333",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/ecommerce-retail/aurum-fine-jewelry/300x250/index.html",
          "kb": 5.1
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/ecommerce-retail/aurum-fine-jewelry/728x90/index.html",
          "kb": 5.3
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/ecommerce-retail/aurum-fine-jewelry/160x600/index.html",
          "kb": 6.2
        }
      }
    },
    {
      "id": 42,
      "slug": "helix-crm",
      "title": "HelixCRM Sales Suite",
      "brand": "Helix CRM",
      "category": "saas-tech",
      "categoryLabel": "SaaS & Tech",
      "style": "split",
      "styleLabel": "Split Panel",
      "industry": "Sales CRM",
      "value": "Split-panel creative that frames pipeline chaos, then the fix.",
      "keywords": [
        "saas",
        "crm",
        "sales",
        "b2b",
        "pipeline"
      ],
      "cta": "Book a Demo",
      "accent": "#14B8A6",
      "border": "#333",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/saas-tech/helix-crm/300x250/index.html",
          "kb": 4.4
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/saas-tech/helix-crm/728x90/index.html",
          "kb": 4.6
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/saas-tech/helix-crm/160x600/index.html",
          "kb": 5.3
        }
      }
    },
    {
      "id": 43,
      "slug": "nest-student-living",
      "title": "Nest Student Living",
      "brand": "Nest",
      "category": "real-estate",
      "categoryLabel": "Real Estate & Architecture",
      "style": "kinetic",
      "styleLabel": "Kinetic Type",
      "industry": "Student Housing",
      "value": "Loud kinetic-type creative aimed at students hunting for rooms.",
      "keywords": [
        "real estate",
        "student",
        "rental",
        "housing",
        "discount"
      ],
      "cta": "Book a Room",
      "accent": "#FF6B35",
      "border": "#333",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/real-estate/nest-student-living/300x250/index.html",
          "kb": 4.9
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/real-estate/nest-student-living/728x90/index.html",
          "kb": 5
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/real-estate/nest-student-living/160x600/index.html",
          "kb": 5
        }
      }
    },
    {
      "id": 44,
      "slug": "taxease-filing",
      "title": "TaxEase Filing",
      "brand": "TaxEase",
      "category": "finance-crypto",
      "categoryLabel": "Finance & Crypto",
      "style": "ticker",
      "styleLabel": "Countdown Ticker",
      "industry": "Tax Software",
      "value": "Deadline countdown creative that drives last-minute tax filing.",
      "keywords": [
        "finance",
        "tax",
        "deadline",
        "free",
        "software"
      ],
      "cta": "File Free Now",
      "accent": "#2563EB",
      "border": "#e2e8f0",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/finance-crypto/taxease-filing/300x250/index.html",
          "kb": 5.7
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/finance-crypto/taxease-filing/728x90/index.html",
          "kb": 5.9
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/finance-crypto/taxease-filing/160x600/index.html",
          "kb": 6.4
        }
      }
    },
    {
      "id": 45,
      "slug": "carelink-telehealth",
      "title": "CareLink Telehealth",
      "brand": "CareLink",
      "category": "healthcare-fitness",
      "categoryLabel": "Healthcare & Fitness",
      "style": "split",
      "styleLabel": "Split Panel",
      "industry": "Telehealth",
      "value": "Reassuring split creative for on-demand video doctor visits.",
      "keywords": [
        "health",
        "telehealth",
        "doctor",
        "healthcare",
        "online"
      ],
      "cta": "Start a Visit",
      "accent": "#0284C7",
      "border": "#e2e8f0",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/healthcare-fitness/carelink-telehealth/300x250/index.html",
          "kb": 4.5
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/healthcare-fitness/carelink-telehealth/728x90/index.html",
          "kb": 4.7
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/healthcare-fitness/carelink-telehealth/160x600/index.html",
          "kb": 5.4
        }
      }
    },
    {
      "id": 46,
      "slug": "snapfit-eyewear",
      "title": "SnapFit Eyewear",
      "brand": "SnapFit",
      "category": "ecommerce-retail",
      "categoryLabel": "E-Commerce & Retail",
      "style": "split",
      "styleLabel": "Split Panel",
      "industry": "Eyewear D2C",
      "value": "Bold split-panel creative promoting free home try-on.",
      "keywords": [
        "eyewear",
        "glasses",
        "fashion",
        "free",
        "d2c"
      ],
      "cta": "Start Try-On",
      "accent": "#2563EB",
      "border": "#e2e8f0",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/ecommerce-retail/snapfit-eyewear/300x250/index.html",
          "kb": 4.5
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/ecommerce-retail/snapfit-eyewear/728x90/index.html",
          "kb": 4.7
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/ecommerce-retail/snapfit-eyewear/160x600/index.html",
          "kb": 5.4
        }
      }
    },
    {
      "id": 47,
      "slug": "quantumcloud-hosting",
      "title": "QuantumCloud Hosting",
      "brand": "QuantumCloud",
      "category": "saas-tech",
      "categoryLabel": "SaaS & Tech",
      "style": "spotlight",
      "styleLabel": "Spotlight Burst",
      "industry": "Cloud Infrastructure",
      "value": "Spotlight creative that puts raw server speed centre stage.",
      "keywords": [
        "saas",
        "hosting",
        "cloud",
        "servers",
        "developer"
      ],
      "cta": "Launch a Server",
      "accent": "#818CF8",
      "border": "#333",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/saas-tech/quantumcloud-hosting/300x250/index.html",
          "kb": 5.9
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/saas-tech/quantumcloud-hosting/728x90/index.html",
          "kb": 6.1
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/saas-tech/quantumcloud-hosting/160x600/index.html",
          "kb": 7
        }
      }
    },
    {
      "id": 48,
      "slug": "harbor-point-prelaunch",
      "title": "Harbor Point Pre-Launch",
      "brand": "Harbor Point",
      "category": "real-estate",
      "categoryLabel": "Real Estate & Architecture",
      "style": "ticker",
      "styleLabel": "Countdown Ticker",
      "industry": "New Developments",
      "value": "Ticker creative with a countdown to close early-bird pricing.",
      "keywords": [
        "real estate",
        "condos",
        "pre-launch",
        "discount",
        "investment"
      ],
      "cta": "Register Now",
      "accent": "#F59E0B",
      "border": "#333",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/real-estate/harbor-point-prelaunch/300x250/index.html",
          "kb": 5.8
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/real-estate/harbor-point-prelaunch/728x90/index.html",
          "kb": 6.1
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/real-estate/harbor-point-prelaunch/160x600/index.html",
          "kb": 6.5
        }
      }
    },
    {
      "id": 49,
      "slug": "greenyield-esg",
      "title": "GreenYield ESG Fund",
      "brand": "GreenYield",
      "category": "finance-crypto",
      "categoryLabel": "Finance & Crypto",
      "style": "editorial",
      "styleLabel": "Editorial Serif",
      "industry": "Sustainable Investing",
      "value": "Considered editorial creative for purpose-led investors.",
      "keywords": [
        "finance",
        "esg",
        "investing",
        "sustainable",
        "funds"
      ],
      "cta": "Explore Funds",
      "accent": "#3F6212",
      "border": "#e2e8f0",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/finance-crypto/greenyield-esg/300x250/index.html",
          "kb": 4.9
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/finance-crypto/greenyield-esg/728x90/index.html",
          "kb": 4.8
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/finance-crypto/greenyield-esg/160x600/index.html",
          "kb": 5.1
        }
      }
    },
    {
      "id": 50,
      "slug": "runclub-marathon",
      "title": "RunClub City Marathon",
      "brand": "RunClub",
      "category": "healthcare-fitness",
      "categoryLabel": "Healthcare & Fitness",
      "style": "ticker",
      "styleLabel": "Countdown Ticker",
      "industry": "Sports Events",
      "value": "Race-day countdown ticker that fills registration before early-bird closes.",
      "keywords": [
        "fitness",
        "running",
        "marathon",
        "event",
        "sports"
      ],
      "cta": "Register Now",
      "accent": "#F97316",
      "border": "#333",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/healthcare-fitness/runclub-marathon/300x250/index.html",
          "kb": 5.7
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/healthcare-fitness/runclub-marathon/728x90/index.html",
          "kb": 5.9
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/healthcare-fitness/runclub-marathon/160x600/index.html",
          "kb": 6.4
        }
      }
    },
    {
      "id": 51,
      "slug": "petpal-premium-food",
      "title": "PetPal Premium Food",
      "brand": "PetPal",
      "category": "ecommerce-retail",
      "categoryLabel": "E-Commerce & Retail",
      "style": "cards",
      "styleLabel": "Card Stack",
      "industry": "Pet Care",
      "value": "Card-stack creative that sells a fresh pet food subscription feature by feature.",
      "keywords": [
        "pets",
        "dog food",
        "subscription",
        "discount",
        "cats"
      ],
      "cta": "Build a Box",
      "accent": "#EA580C",
      "border": "#e2e8f0",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/ecommerce-retail/petpal-premium-food/300x250/index.html",
          "kb": 6.1
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/ecommerce-retail/petpal-premium-food/728x90/index.html",
          "kb": 5.7
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/ecommerce-retail/petpal-premium-food/160x600/index.html",
          "kb": 6.3
        }
      }
    },
    {
      "id": 52,
      "slug": "pixelforge-design",
      "title": "PixelForge Design Tool",
      "brand": "PixelForge",
      "category": "saas-tech",
      "categoryLabel": "SaaS & Tech",
      "style": "blob",
      "styleLabel": "Organic Blobs",
      "industry": "Design SaaS",
      "value": "Playful morphing-blob creative for a collaborative design tool.",
      "keywords": [
        "saas",
        "design",
        "ui",
        "collaboration",
        "prototyping"
      ],
      "cta": "Design Free",
      "accent": "#A855F7",
      "border": "#e2e8f0",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/saas-tech/pixelforge-design/300x250/index.html",
          "kb": 5.1
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/saas-tech/pixelforge-design/728x90/index.html",
          "kb": 5.3
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/saas-tech/pixelforge-design/160x600/index.html",
          "kb": 6.1
        }
      }
    },
    {
      "id": 53,
      "slug": "crestview-family-homes",
      "title": "Crestview Family Homes",
      "brand": "Crestview",
      "category": "real-estate",
      "categoryLabel": "Real Estate & Architecture",
      "style": "cards",
      "styleLabel": "Card Stack",
      "industry": "Residential Sales",
      "value": "Feature-card creative that walks families through a home's best bits.",
      "keywords": [
        "real estate",
        "homes",
        "family",
        "open house",
        "residential"
      ],
      "cta": "Book a Viewing",
      "accent": "#EA580C",
      "border": "#e2e8f0",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/real-estate/crestview-family-homes/300x250/index.html",
          "kb": 5.4
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/real-estate/crestview-family-homes/728x90/index.html",
          "kb": 5
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/real-estate/crestview-family-homes/160x600/index.html",
          "kb": 5.6
        }
      }
    },
    {
      "id": 54,
      "slug": "swiftsend-remittance",
      "title": "SwiftSend Remittance",
      "brand": "SwiftSend",
      "category": "finance-crypto",
      "categoryLabel": "Finance & Crypto",
      "style": "split",
      "styleLabel": "Split Panel",
      "industry": "Money Transfer",
      "value": "Split-panel creative promising fast, fair cross-border transfers.",
      "keywords": [
        "finance",
        "remittance",
        "transfer",
        "fintech",
        "free"
      ],
      "cta": "Send Now",
      "accent": "#7C3AED",
      "border": "#e2e8f0",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/finance-crypto/swiftsend-remittance/300x250/index.html",
          "kb": 4.4
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/finance-crypto/swiftsend-remittance/728x90/index.html",
          "kb": 4.7
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/finance-crypto/swiftsend-remittance/160x600/index.html",
          "kb": 5.4
        }
      }
    },
    {
      "id": 55,
      "slug": "vitaboost-supplements",
      "title": "VitaBoost Supplements",
      "brand": "VitaBoost",
      "category": "healthcare-fitness",
      "categoryLabel": "Healthcare & Fitness",
      "style": "cards",
      "styleLabel": "Card Stack",
      "industry": "Nutrition & Supplements",
      "value": "Card-stack creative that sells personalised vitamin packs.",
      "keywords": [
        "health",
        "vitamins",
        "supplements",
        "subscription",
        "discount"
      ],
      "cta": "Take the Quiz",
      "accent": "#D97706",
      "border": "#e2e8f0",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/healthcare-fitness/vitaboost-supplements/300x250/index.html",
          "kb": 6.1
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/healthcare-fitness/vitaboost-supplements/728x90/index.html",
          "kb": 5.6
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/healthcare-fitness/vitaboost-supplements/160x600/index.html",
          "kb": 6.3
        }
      }
    },
    {
      "id": 56,
      "slug": "voltra-ebikes",
      "title": "Voltra E-Bikes",
      "brand": "Voltra",
      "category": "ecommerce-retail",
      "categoryLabel": "E-Commerce & Retail",
      "style": "data",
      "styleLabel": "Live Data Chart",
      "industry": "Micromobility",
      "value": "Data-driven creative that counts up real range stats for an e-bike launch.",
      "keywords": [
        "ebike",
        "bikes",
        "electric",
        "commute",
        "test ride"
      ],
      "cta": "Book Test Ride",
      "accent": "#A3E635",
      "border": "#333",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/ecommerce-retail/voltra-ebikes/300x250/index.html",
          "kb": 5.3
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/ecommerce-retail/voltra-ebikes/728x90/index.html",
          "kb": 5.7
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/ecommerce-retail/voltra-ebikes/160x600/index.html",
          "kb": 6.4
        }
      }
    },
    {
      "id": 57,
      "slug": "lingua-ai-translate",
      "title": "LinguaAI Translate",
      "brand": "LinguaAI",
      "category": "saas-tech",
      "categoryLabel": "SaaS & Tech",
      "style": "editorial",
      "styleLabel": "Editorial Serif",
      "industry": "AI Translation",
      "value": "Editorial serif creative that sells nuance, not just translation.",
      "keywords": [
        "saas",
        "ai",
        "translation",
        "language",
        "localization"
      ],
      "cta": "Translate Free",
      "accent": "#B91C1C",
      "border": "#e2e8f0",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/saas-tech/lingua-ai-translate/300x250/index.html",
          "kb": 4.7
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/saas-tech/lingua-ai-translate/728x90/index.html",
          "kb": 4.6
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/saas-tech/lingua-ai-translate/160x600/index.html",
          "kb": 4.9
        }
      }
    },
    {
      "id": 58,
      "slug": "neon-district-lofts",
      "title": "Neon District Lofts",
      "brand": "Neon District",
      "category": "real-estate",
      "categoryLabel": "Real Estate & Architecture",
      "style": "neon",
      "styleLabel": "Neon Glitch",
      "industry": "Urban Rentals",
      "value": "After-dark neon creative for nightlife-ready city lofts.",
      "keywords": [
        "real estate",
        "lofts",
        "rental",
        "urban",
        "nightlife"
      ],
      "cta": "Tour Tonight",
      "accent": "#F0ABFC",
      "border": "#333",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/real-estate/neon-district-lofts/300x250/index.html",
          "kb": 6.1
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/real-estate/neon-district-lofts/728x90/index.html",
          "kb": 6.1
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/real-estate/neon-district-lofts/160x600/index.html",
          "kb": 7.1
        }
      }
    },
    {
      "id": 59,
      "slug": "fortis-business-loans",
      "title": "Fortis Business Loans",
      "brand": "Fortis Capital",
      "category": "finance-crypto",
      "categoryLabel": "Finance & Crypto",
      "style": "cards",
      "styleLabel": "Card Stack",
      "industry": "SME Lending",
      "value": "Card-stack creative that answers a business owner's three big questions.",
      "keywords": [
        "finance",
        "business",
        "loans",
        "sme",
        "funding"
      ],
      "cta": "Get Funded",
      "accent": "#3B82F6",
      "border": "#333",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/finance-crypto/fortis-business-loans/300x250/index.html",
          "kb": 5.5
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/finance-crypto/fortis-business-loans/728x90/index.html",
          "kb": 5.1
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/finance-crypto/fortis-business-loans/160x600/index.html",
          "kb": 5.8
        }
      }
    },
    {
      "id": 60,
      "slug": "sleepwell-mattress",
      "title": "SleepWell Smart Mattress",
      "brand": "SleepWell",
      "category": "healthcare-fitness",
      "categoryLabel": "Healthcare & Fitness",
      "style": "data",
      "styleLabel": "Live Data Chart",
      "industry": "Sleep Tech",
      "value": "Night-mode data creative that charts better sleep scores.",
      "keywords": [
        "health",
        "sleep",
        "mattress",
        "smart home",
        "wellness"
      ],
      "cta": "Try 100 Nights",
      "accent": "#A78BFA",
      "border": "#333",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/healthcare-fitness/sleepwell-mattress/300x250/index.html",
          "kb": 5.2
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/healthcare-fitness/sleepwell-mattress/728x90/index.html",
          "kb": 5.7
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/healthcare-fitness/sleepwell-mattress/160x600/index.html",
          "kb": 6.4
        }
      }
    },
    {
      "id": 61,
      "slug": "glacier-outdoor-gear",
      "title": "Glacier Outdoor Gear",
      "brand": "Glacier",
      "category": "ecommerce-retail",
      "categoryLabel": "E-Commerce & Retail",
      "style": "kinetic",
      "styleLabel": "Kinetic Type",
      "industry": "Outdoor Apparel",
      "value": "Punchy kinetic-type creative for a summit-ready gear sale.",
      "keywords": [
        "outdoor",
        "hiking",
        "apparel",
        "discount",
        "adventure"
      ],
      "cta": "Gear Up",
      "accent": "#F97316",
      "border": "#333",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/ecommerce-retail/glacier-outdoor-gear/300x250/index.html",
          "kb": 4.8
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/ecommerce-retail/glacier-outdoor-gear/728x90/index.html",
          "kb": 4.9
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/ecommerce-retail/glacier-outdoor-gear/160x600/index.html",
          "kb": 5
        }
      }
    },
    {
      "id": 62,
      "slug": "securevault-passwords",
      "title": "SecureVault Passwords",
      "brand": "SecureVault",
      "category": "saas-tech",
      "categoryLabel": "SaaS & Tech",
      "style": "ticker",
      "styleLabel": "Countdown Ticker",
      "industry": "Cybersecurity",
      "value": "Countdown-driven creative that turns password hygiene into a limited-time deal.",
      "keywords": [
        "saas",
        "security",
        "passwords",
        "discount",
        "privacy"
      ],
      "cta": "Secure My Logins",
      "accent": "#F97316",
      "border": "#333",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/saas-tech/securevault-passwords/300x250/index.html",
          "kb": 6.4
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/saas-tech/securevault-passwords/728x90/index.html",
          "kb": 6.7
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/saas-tech/securevault-passwords/160x600/index.html",
          "kb": 7.1
        }
      }
    },
    {
      "id": 63,
      "slug": "horizon-coworking",
      "title": "Horizon Coworking",
      "brand": "Horizon Work",
      "category": "real-estate",
      "categoryLabel": "Real Estate & Architecture",
      "style": "split",
      "styleLabel": "Split Panel",
      "industry": "Flexible Workspace",
      "value": "Mirrored split creative with a free day-pass hook.",
      "keywords": [
        "real estate",
        "coworking",
        "office",
        "flexible",
        "free"
      ],
      "cta": "Claim Free Day",
      "accent": "#E11D48",
      "border": "#e2e8f0",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/real-estate/horizon-coworking/300x250/index.html",
          "kb": 4.5
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/real-estate/horizon-coworking/728x90/index.html",
          "kb": 4.7
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/real-estate/horizon-coworking/160x600/index.html",
          "kb": 5.4
        }
      }
    },
    {
      "id": 64,
      "slug": "coinpulse-exchange",
      "title": "CoinPulse Exchange",
      "brand": "CoinPulse",
      "category": "finance-crypto",
      "categoryLabel": "Finance & Crypto",
      "style": "kinetic",
      "styleLabel": "Kinetic Type",
      "industry": "Crypto Exchange",
      "value": "Fast-cut kinetic creative for a low-fee crypto exchange.",
      "keywords": [
        "crypto",
        "exchange",
        "trading",
        "bonus",
        "bitcoin"
      ],
      "cta": "Sign Up",
      "accent": "#00E676",
      "border": "#333",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/finance-crypto/coinpulse-exchange/300x250/index.html",
          "kb": 4.9
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/finance-crypto/coinpulse-exchange/728x90/index.html",
          "kb": 5
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/finance-crypto/coinpulse-exchange/160x600/index.html",
          "kb": 5.1
        }
      }
    },
    {
      "id": 65,
      "slug": "pulseride-spin",
      "title": "PulseRide Spin Bike",
      "brand": "PulseRide",
      "category": "healthcare-fitness",
      "categoryLabel": "Healthcare & Fitness",
      "style": "neon",
      "styleLabel": "Neon Glitch",
      "industry": "Connected Fitness",
      "value": "Studio-light neon creative for live at-home spin classes.",
      "keywords": [
        "fitness",
        "spin",
        "cycling",
        "home workout",
        "classes"
      ],
      "cta": "Start Riding",
      "accent": "#FF2E63",
      "border": "#333",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/healthcare-fitness/pulseride-spin/300x250/index.html",
          "kb": 6.1
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/healthcare-fitness/pulseride-spin/728x90/index.html",
          "kb": 6.1
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/healthcare-fitness/pulseride-spin/160x600/index.html",
          "kb": 7.1
        }
      }
    },
    {
      "id": 66,
      "slug": "luma-smart-home",
      "title": "Luma Smart Home",
      "brand": "Luma",
      "category": "ecommerce-retail",
      "categoryLabel": "E-Commerce & Retail",
      "style": "split",
      "styleLabel": "Split Panel",
      "industry": "Smart Home",
      "value": "Mirrored split creative for a smart lighting starter kit.",
      "keywords": [
        "smart home",
        "lighting",
        "iot",
        "gadgets",
        "kit"
      ],
      "cta": "Shop the Kit",
      "accent": "#FACC15",
      "border": "#333",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/ecommerce-retail/luma-smart-home/300x250/index.html",
          "kb": 4.5
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/ecommerce-retail/luma-smart-home/728x90/index.html",
          "kb": 4.7
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/ecommerce-retail/luma-smart-home/160x600/index.html",
          "kb": 5.4
        }
      }
    },
    {
      "id": 67,
      "slug": "stackly-nocode",
      "title": "Stackly No-Code",
      "brand": "Stackly",
      "category": "saas-tech",
      "categoryLabel": "SaaS & Tech",
      "style": "data",
      "styleLabel": "Live Data Chart",
      "industry": "No-Code Platform",
      "value": "Rising bar-chart creative that quantifies faster app delivery.",
      "keywords": [
        "saas",
        "no-code",
        "apps",
        "startups",
        "productivity"
      ],
      "cta": "Build Free",
      "accent": "#4F46E5",
      "border": "#e2e8f0",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/saas-tech/stackly-nocode/300x250/index.html",
          "kb": 5
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/saas-tech/stackly-nocode/728x90/index.html",
          "kb": 5.4
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/saas-tech/stackly-nocode/160x600/index.html",
          "kb": 6.1
        }
      }
    },
    {
      "id": 68,
      "slug": "palazzo-heritage",
      "title": "Palazzo Heritage Residences",
      "brand": "Palazzo",
      "category": "real-estate",
      "categoryLabel": "Real Estate & Architecture",
      "style": "spotlight",
      "styleLabel": "Spotlight Burst",
      "industry": "Heritage Restoration",
      "value": "Spotlit, gilded creative for restored landmark apartments.",
      "keywords": [
        "real estate",
        "heritage",
        "luxury",
        "architecture",
        "apartments"
      ],
      "cta": "Private Viewing",
      "accent": "#D6B370",
      "border": "#333",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/real-estate/palazzo-heritage/300x250/index.html",
          "kb": 5.1
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/real-estate/palazzo-heritage/728x90/index.html",
          "kb": 5.3
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/real-estate/palazzo-heritage/160x600/index.html",
          "kb": 6.3
        }
      }
    },
    {
      "id": 69,
      "slug": "pensionplus-retirement",
      "title": "PensionPlus Retirement",
      "brand": "PensionPlus",
      "category": "finance-crypto",
      "categoryLabel": "Finance & Crypto",
      "style": "data",
      "styleLabel": "Live Data Chart",
      "industry": "Retirement Planning",
      "value": "Growth-curve creative that visualises a retirement pot compounding.",
      "keywords": [
        "finance",
        "retirement",
        "pension",
        "investing",
        "planning"
      ],
      "cta": "Plan My Future",
      "accent": "#EA580C",
      "border": "#e2e8f0",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/finance-crypto/pensionplus-retirement/300x250/index.html",
          "kb": 5.4
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/finance-crypto/pensionplus-retirement/728x90/index.html",
          "kb": 5.8
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/finance-crypto/pensionplus-retirement/160x600/index.html",
          "kb": 6.5
        }
      }
    },
    {
      "id": 70,
      "slug": "smilebright-whitening",
      "title": "SmileBright Whitening",
      "brand": "SmileBright",
      "category": "healthcare-fitness",
      "categoryLabel": "Healthcare & Fitness",
      "style": "kinetic",
      "styleLabel": "Kinetic Type",
      "industry": "Dental Care",
      "value": "Bright, light-mode kinetic creative for an at-home whitening kit.",
      "keywords": [
        "health",
        "dental",
        "whitening",
        "beauty",
        "discount"
      ],
      "cta": "Get My Kit",
      "accent": "#0891B2",
      "border": "#e2e8f0",
      "sizes": {
        "300x250": {
          "w": 300,
          "h": 250,
          "name": "Medium Rectangle",
          "path": "ads/healthcare-fitness/smilebright-whitening/300x250/index.html",
          "kb": 5
        },
        "728x90": {
          "w": 728,
          "h": 90,
          "name": "Leaderboard",
          "path": "ads/healthcare-fitness/smilebright-whitening/728x90/index.html",
          "kb": 5.1
        },
        "160x600": {
          "w": 160,
          "h": 600,
          "name": "Wide Skyscraper",
          "path": "ads/healthcare-fitness/smilebright-whitening/160x600/index.html",
          "kb": 5.2
        }
      }
    }
  ]
};
