#!/usr/bin/env node
/**
 * AdStudioLab banner builder.
 *
 * Generates every self-contained GDN banner in ads/<category>/<campaign>/<size>/index.html
 * plus the showcase registry in scripts/data.js (with measured file payloads).
 *
 *   lib/campaigns-original.mjs  campaigns 1–20 (Classic Hero style)
 *   lib/campaigns-new.mjs       campaigns 21–70 (nine newer creative styles)
 *   lib/styles.mjs              the creative styles
 *
 * Edit the campaign files, then run:  node tools/build-ads.mjs
 */
import { mkdirSync, writeFileSync, statSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { SIZES, GSAP_URL, GSAP_KB, CLICK_URL, LOOP, PLAYS, GAP, TOTAL } from "./lib/util.mjs";
import { ORIGINAL } from "./lib/campaigns-original.mjs";
import { NEW_BY_CATEGORY } from "./lib/campaigns-new.mjs";
import { classicPage } from "./lib/style-classic.mjs";
import { buildStyled, STYLES, STYLE_LABELS } from "./lib/styles.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

const CATEGORIES = [
  { slug: "ecommerce-retail", label: "E-Commerce & Retail" },
  { slug: "saas-tech", label: "SaaS & Tech" },
  { slug: "real-estate", label: "Real Estate & Architecture" },
  { slug: "finance-crypto", label: "Finance & Crypto" },
  { slug: "healthcare-fitness", label: "Healthcare & Fitness" },
];

// Originals keep ids 1–20; new campaigns are interleaved across categories so "All" mixes styles
const interleaved = [];
const perCategory = Math.max(...Object.values(NEW_BY_CATEGORY).map((list) => list.length));
for (let i = 0; i < perCategory; i++) {
  for (const cat of CATEGORIES) {
    const c = NEW_BY_CATEGORY[cat.slug]?.[i];
    if (c) interleaved.push({ ...c, category: cat.slug });
  }
}
const CAMPAIGNS = [...ORIGINAL.map((c) => ({ ...c, style: "classic" })), ...interleaved].map((c, i) => ({ ...c, id: i + 1 }));

/* ------------------------------------------------------------------ */
/* Validate before writing anything                                    */
/* ------------------------------------------------------------------ */
const NEEDS = {
  split: ["intro", "features"],
  kinetic: ["intro"],
  cards: ["features"],
  data: ["stat", "features"],
  spotlight: ["intro"],
  ticker: ["offer"],
  neon: ["intro", "features"],
  blob: ["intro", "features"],
};
const seen = new Set();
for (const c of CAMPAIGNS) {
  const where = `campaign #${c.id} "${c.slug}"`;
  if (seen.has(c.slug)) throw new Error(`Duplicate slug in ${where}`);
  seen.add(c.slug);
  if (c.style !== "classic" && !STYLES[c.style]) throw new Error(`Unknown style "${c.style}" in ${where}`);
  if (!CATEGORIES.some((cat) => cat.slug === c.category)) throw new Error(`Unknown category "${c.category}" in ${where}`);
  for (const field of ["title", "brand", "industry", "icon", "value", "keywords", "headline", "sub", "cta", "theme", ...(NEEDS[c.style] || [])]) {
    if (!c[field]) throw new Error(`Missing "${field}" in ${where}`);
  }
}

/* ------------------------------------------------------------------ */
/* Write banners + registry                                            */
/* ------------------------------------------------------------------ */
const catLabel = Object.fromEntries(CATEGORIES.map((c) => [c.slug, c.label]));

const campaigns = CAMPAIGNS.map((c) => {
  const sizes = {};
  for (const key of Object.keys(SIZES)) {
    const rel = `ads/${c.category}/${c.slug}/${key}/index.html`;
    const file = join(ROOT, rel);
    mkdirSync(dirname(file), { recursive: true });
    writeFileSync(file, c.style === "classic" ? classicPage(c, key) : buildStyled(c, key));
    const kb = +(statSync(file).size / 1024).toFixed(1);
    sizes[key] = { w: SIZES[key].w, h: SIZES[key].h, name: SIZES[key].name, path: rel, kb };
  }
  return {
    id: c.id,
    slug: c.slug,
    title: c.title,
    brand: c.brand,
    category: c.category,
    categoryLabel: catLabel[c.category],
    style: c.style,
    styleLabel: STYLE_LABELS[c.style],
    industry: c.industry,
    value: c.value,
    keywords: c.keywords,
    cta: c.cta,
    accent: c.theme.accent,
    border: c.theme.border,
    sizes,
  };
});

const registry = {
  gsap: { version: "3.12.2", url: GSAP_URL, kb: GSAP_KB },
  clickTag: CLICK_URL,
  animation: { loop: LOOP, plays: PLAYS, pause: GAP, total: TOTAL },
  categories: CATEGORIES,
  styles: Object.entries(STYLE_LABELS).map(([slug, label]) => ({ slug, label })),
  campaigns,
};

mkdirSync(join(ROOT, "scripts"), { recursive: true });
writeFileSync(
  join(ROOT, "scripts/data.js"),
  `/* Generated by tools/build-ads.mjs — edit campaigns there and re-run: node tools/build-ads.mjs */\n` +
    `window.ADSTUDIO = ${JSON.stringify(registry, null, 2)};\n`
);

const all = campaigns.flatMap((c) => Object.values(c.sizes).map((s) => s.kb));
const byStyle = campaigns.reduce((acc, c) => ((acc[c.style] = (acc[c.style] || 0) + 1), acc), {});
console.log(`Built ${all.length} banners for ${campaigns.length} campaigns.`);
console.log(`Styles: ${Object.entries(byStyle).map(([s, n]) => `${s} ${n}`).join(", ")}`);
console.log(`HTML payload: min ${Math.min(...all)} KB, max ${Math.max(...all)} KB (+ GSAP ${GSAP_KB.gzip} KB gzipped).`);
